SSAnne_2F_Room5_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
    .string "Have you gone to the SAFARI ZONE\n"
    .string "in Fuchsia City?\p"
    .string "There are many kinds of rare\n"
    .string "Pokémon.$"

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
    .string "Me and my granpa think the Safari\n"
    .string "Zone is awesome!\l"
    .string "I wish we could go there again.$"
