SaffronCity_PokemonCenter_2F_MapScripts::
	.byte 0

SaffronCity_PokemonCenter_2F_Rocket1::
	msgbox SaffronCity_PokemonCenter_2F_Text_Rocket1, MSGBOX_NPC
	release
	end

SaffronCity_PokemonCenter_2F_Text_Rocket1::
	.string "Heh, scram kid!\n"
	.string "This is Team Rocket's Loot now!$"


SaffronCity_PokemonCenter_2F_Rocket2::
	msgbox SaffronCity_PokemonCenter_2F_Text_Rocket2, MSGBOX_NPC
	release
	end

SaffronCity_PokemonCenter_2F_Text_Rocket2::
	.string "Uh..I forgot what we came here for.$"

SaffronCity_PokemonCenter_2F_Rocket3::
	msgbox SaffronCity_PokemonCenter_2F_Text_Rocket3, MSGBOX_NPC
	release
	end

SaffronCity_PokemonCenter_2F_Text_Rocket3::
	.string "Whoa! They have some really rare\n"
	.string "goods back here!\p"
	.string "The Boss is going to love this haul!$"
