#ifndef GUARD_CONSTANTS_BERRY_H
#define GUARD_CONSTANTS_BERRY_H

#define BERRY_NONE 0

#define BERRY_FIRMNESS_UNKNOWN     0
#define BERRY_FIRMNESS_VERY_SOFT   1
#define BERRY_FIRMNESS_SOFT        2
#define BERRY_FIRMNESS_HARD        3
#define BERRY_FIRMNESS_VERY_HARD   4
#define BERRY_FIRMNESS_SUPER_HARD  5

#define FLAVOR_SPICY   0
#define FLAVOR_DRY     1
#define FLAVOR_SWEET   2
#define FLAVOR_BITTER  3
#define FLAVOR_SOUR    4
#define FLAVOR_COUNT   5

#define BERRY_STAGE_NO_BERRY    0  // there is no tree planted and the soil is completely flat.
#define BERRY_STAGE_PLANTED     1
#define BERRY_STAGE_SPROUTED    2
#define BERRY_STAGE_TALLER      3
#define BERRY_STAGE_FLOWERING   4
#define BERRY_STAGE_BERRIES     5
#define BERRY_STAGE_SPARKLING   255

// Berries can be watered in the following stages:
// - BERRY_STAGE_PLANTED
// - BERRY_STAGE_SPROUTED
// - BERRY_STAGE_TALLER
// - BERRY_STAGE_FLOWERING
#define NUM_WATER_STAGES 4

// IDs for berry tree objects, indexes into berryTrees in SaveBlock1
// Named for whatever berry is initially planted there on a new game
// Those with no initial berry are named "soil"

#define BERRY_TREE_ROUTE_1_PECHA    	1
#define BERRY_TREE_ROUTE_1_ORAN 		2

#define BERRY_TREE_ROUTE_2_ORAN 		3
#define BERRY_TREE_ROUTE_2_PECHA 		4
#define BERRY_TREE_ROUTE_2_BELUE_1 	  	5
#define BERRY_TREE_ROUTE_2_BELUE_2    	6
#define BERRY_TREE_ROUTE_2_DURIN_1  	7
#define BERRY_TREE_ROUTE_2_DURIN_2  	8
#define BERRY_TREE_ROUTE_2_LUM  		9

#define BERRY_TREE_ROUTE_3_PERSIM   	10
#define BERRY_TREE_ROUTE_3_PECHA 		11
#define BERRY_TREE_ROUTE_3_ORAN   		12

#define BERRY_TREE_ROUTE_4_ORAN_1	   	13
#define BERRY_TREE_ROUTE_4_ORAN_2	 	14
#define BERRY_TREE_ROUTE_4_WATMEL	  	15
#define BERRY_TREE_ROUTE_4_PAMTRE  		16

#define BERRY_TREE_CERULEAN_WEPEAR  	17
#define BERRY_TREE_CERULEAN_PINAP  		18
#define BERRY_TREE_CERULEAN_NANAB   	19

#define BERRY_TREE_ROUTE_5_POMEG   		20
#define BERRY_TREE_ROUTE_5_KELPSY  		21
#define BERRY_TREE_ROUTE_5_QUALOT  		22
#define BERRY_TREE_ROUTE_5_HONDEW  		23
#define BERRY_TREE_ROUTE_5_GREPA  		24
#define BERRY_TREE_ROUTE_5_TAMATO  		25

#define BERRY_TREE_ROUTE_6_SOIL_1		26
#define BERRY_TREE_ROUTE_6_SOIL_2 		27
#define BERRY_TREE_ROUTE_6_SOIL_3 		28
#define BERRY_TREE_ROUTE_6_SOIL_4 		29
#define BERRY_TREE_ROUTE_6_SOIL_5  		30
#define BERRY_TREE_ROUTE_6_ORAN_1 		31
#define BERRY_TREE_ROUTE_6_CHERI     	32
#define BERRY_TREE_ROUTE_6_ORAN_2 		33
#define BERRY_TREE_ROUTE_6_SITRUS  		34

#define BERRY_TREE_ROUTE_7_LEPPA		35

#define BERRY_TREE_ROUTE_8_SPELON  		36
#define BERRY_TREE_ROUTE_8_NOMEL 		37
#define BERRY_TREE_ROUTE_8_RABUTA 		38

#define BERRY_TREE_ROUTE_9_CHESTO 		39

#define BERRY_TREE_ROUTE_10_FIGY  		40
#define BERRY_TREE_ROUTE_10_PERSIM_1  	41
#define BERRY_TREE_ROUTE_10_PERSIM_2  	42

#define BERRY_TREE_ROUTE_11_SITRUS     	43
#define BERRY_TREE_ROUTE_11_CHERI     	44
#define BERRY_TREE_ROUTE_11_SOIL_1     	45
#define BERRY_TREE_ROUTE_11_SOIL_2     	46

#define BERRY_TREE_ROUTE_12_LUM    		47

#define BERRY_TREE_ROUTE_13_IAPAPA   	48
#define BERRY_TREE_ROUTE_13_RAZZ   		49
#define BERRY_TREE_ROUTE_13_BLUK		50

#define BERRY_TREE_ROUTE_14_RAWST   	51
#define BERRY_TREE_ROUTE_14_WIKI    	52

#define BERRY_TREE_ROUTE_15_MAGO_1   	53
#define BERRY_TREE_ROUTE_15_MAGO_2   	54
#define BERRY_TREE_ROUTE_15_MAGOST  	55

#define BERRY_TREE_ROUTE_16_ASPEAR  	56
#define BERRY_TREE_ROUTE_16_SOIL_1   	57
#define BERRY_TREE_ROUTE_16_SOIL_2   	58
#define BERRY_TREE_ROUTE_16_SOIL_3   	59

#define BERRY_TREE_ROUTE_18_CORNN     	60
#define BERRY_TREE_ROUTE_18_AGUAV  		61

#define BERRY_TREE_FUCHSIA_SOIL_1     	62
#define BERRY_TREE_FUCHSIA_SOIL_2    	63
#define BERRY_TREE_FUCHSIA_SOIL_3 		64

#define BERRY_TREE_PEWTER_SOIL_1     	65
#define BERRY_TREE_PEWTER_SOIL_2    	66
#define BERRY_TREE_PEWTER_SOIL_3  		67
#define BERRY_TREE_PEWTER_ORAN     		68
#define BERRY_TREE_PEWTER_PERSIM    	69
#define BERRY_TREE_PEWTER_PECHA  		70

#define BERRY_TREE_VIRIDIAN_SOIL     	71

#define BERRY_TREE_ROUTE_10_SOIL_1  	72
#define BERRY_TREE_ROUTE_10_SOIL_2  	73

#define BERRY_TREE_BATTLE_TOWER_SOIL_1 	74
#define BERRY_TREE_BATTLE_TOWER_SOIL_2  75
#define BERRY_TREE_BATTLE_TOWER_SOIL_3  76
#define BERRY_TREE_BATTLE_TOWER_SOIL_4  77

// Remainder are unused

#define BERRY_TREES_COUNT 128

#endif // GUARD_CONSTANTS_BERRY_H
