#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

//Player Characters
#define OBJ_EVENT_GFX_BRENDAN_NORMAL 				0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            	1
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE 			2
#define OBJ_EVENT_GFX_BRENDAN_SURFING               3
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           	4
#define OBJ_EVENT_GFX_BRENDAN_WATERING           	5
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         	6
#define OBJ_EVENT_GFX_BRENDAN_FISHING            	7
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         	8

#define OBJ_EVENT_GFX_MAY_NORMAL                 	9
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               	10
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               	11
#define OBJ_EVENT_GFX_MAY_SURFING                 	12
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              	13
#define OBJ_EVENT_GFX_MAY_WATERING               	14
#define OBJ_EVENT_GFX_MAY_DECORATING             	15
#define OBJ_EVENT_GFX_MAY_FISHING                	16
#define OBJ_EVENT_GFX_MAY_UNDERWATER             	17

//Rival GFX
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       	18
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    	19
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    	20
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      	21
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   	22

#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           	23
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        	24
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        	25
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          	26
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       	27

//Link Brendan/May
#define OBJ_EVENT_GFX_LINK_BRENDAN               	28
#define OBJ_EVENT_GFX_LINK_MAY                   	29
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            	30
#define OBJ_EVENT_GFX_LINK_RS_MAY                	31

#define OBJ_EVENT_GFX_ANIMATED_BALL              	32
#define OBJ_EVENT_GFX_OW_MON                     	33

#define OBJECT_GFX									OBJ_EVENT_GFX_OW_MON 

//Objects
#define OBJ_EVENT_GFX_ITEM_BALL                   	OBJECT_GFX + 1
#define OBJ_EVENT_GFX_BERRY_TREE                  	OBJECT_GFX + 2
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     	OBJECT_GFX + 3
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      	OBJECT_GFX + 4
#define OBJ_EVENT_GFX_FOSSIL                     	OBJECT_GFX + 5
#define OBJ_EVENT_GFX_CUTTABLE_TREE               	OBJECT_GFX + 6
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              	OBJECT_GFX + 7
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            	OBJECT_GFX + 8
#define OBJ_EVENT_GFX_GREAT_BALL                	OBJECT_GFX + 9
#define OBJ_EVENT_GFX_ULTRA_BALL                	OBJECT_GFX + 10
#define OBJ_EVENT_GFX_MASTER_BALL               	OBJECT_GFX + 11
#define OBJ_EVENT_GFX_SAFARI_BALL               	OBJECT_GFX + 12
#define OBJ_EVENT_GFX_PREMIER_BALL					OBJECT_GFX + 13
#define OBJ_EVENT_GFX_TRUCK                       	OBJECT_GFX + 14
#define OBJ_EVENT_GFX_MOVING_BOX                 	OBJECT_GFX + 15
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       	OBJECT_GFX + 16
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        	OBJECT_GFX + 17
#define OBJ_EVENT_GFX_BIRCHS_BAG                  	OBJECT_GFX + 18
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             	OBJECT_GFX + 19
#define OBJ_EVENT_GFX_SS_TIDAL                   	OBJECT_GFX + 20
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         	OBJECT_GFX + 21
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           	OBJECT_GFX + 22
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW     	OBJECT_GFX + 23
#define OBJ_EVENT_GFX_CABLE_CAR                  	OBJECT_GFX + 24
#define OBJ_EVENT_GFX_POKEDEX						OBJECT_GFX + 25
#define OBJ_EVENT_GFX_SS_ANNE						OBJECT_GFX + 26
#define OBJ_EVENT_GFX_OLD_AMBER						OBJECT_GFX + 27
#define OBJ_EVENT_GFX_CLIPBOARD						OBJECT_GFX + 28
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            	OBJECT_GFX + 29

#define	COSTUME_GFX									OBJ_EVENT_GFX_DEOXYS_TRIANGLE 

//Costumes
#define OBJ_EVENT_GFX_RED_NORMAL     				COSTUME_GFX + 1
#define OBJ_EVENT_GFX_RED_FIELD_MOVE     			COSTUME_GFX + 2
#define OBJ_EVENT_GFX_RED_SURFING        			COSTUME_GFX + 3
#define OBJ_EVENT_GFX_RED_MACH_BIKE      			COSTUME_GFX + 4
#define OBJ_EVENT_GFX_RED_ACRO_BIKE      			COSTUME_GFX + 5
#define OBJ_EVENT_GFX_RED_FISHING        			COSTUME_GFX + 6
#define OBJ_EVENT_GFX_RED_WATERING      			COSTUME_GFX + 7
#define OBJ_EVENT_GFX_RED_DECORATING     			COSTUME_GFX + 8
#define OBJ_EVENT_GFX_RED_UNDERWATER     			COSTUME_GFX + 9

#define OBJ_EVENT_GFX_LEAF_NORMAL 					COSTUME_GFX + 10
#define OBJ_EVENT_GFX_LEAF_FIELD_MOVE         		COSTUME_GFX + 11
#define OBJ_EVENT_GFX_LEAF_SURFING            		COSTUME_GFX + 12
#define OBJ_EVENT_GFX_LEAF_MACH_BIKE          		COSTUME_GFX + 13
#define OBJ_EVENT_GFX_LEAF_ACRO_BIKE          		COSTUME_GFX + 14
#define OBJ_EVENT_GFX_LEAF_FISHING            		COSTUME_GFX + 15
#define OBJ_EVENT_GFX_LEAF_WATERING           		COSTUME_GFX + 16
#define OBJ_EVENT_GFX_LEAF_DECORATING         		COSTUME_GFX + 17
#define OBJ_EVENT_GFX_LEAF_UNDERWATER         		COSTUME_GFX + 18

#define OBJ_EVENT_GFX_ETHAN_NORMAL 					COSTUME_GFX + 19
#define OBJ_EVENT_GFX_ETHAN_FIELD_MOVE         		COSTUME_GFX + 20
#define OBJ_EVENT_GFX_ETHAN_SURFING            		COSTUME_GFX + 21
#define OBJ_EVENT_GFX_ETHAN_MACH_BIKE          		COSTUME_GFX + 22
#define OBJ_EVENT_GFX_ETHAN_ACRO_BIKE          		COSTUME_GFX + 23
#define OBJ_EVENT_GFX_ETHAN_FISHING            		COSTUME_GFX + 24
#define OBJ_EVENT_GFX_ETHAN_WATERING           		COSTUME_GFX + 25
#define OBJ_EVENT_GFX_ETHAN_DECORATING         		COSTUME_GFX + 26
#define OBJ_EVENT_GFX_ETHAN_UNDERWATER         		COSTUME_GFX + 27

#define OBJ_EVENT_GFX_LYRA_NORMAL 					COSTUME_GFX + 28
#define OBJ_EVENT_GFX_LYRA_FIELD_MOVE         		COSTUME_GFX + 29
#define OBJ_EVENT_GFX_LYRA_SURFING            		COSTUME_GFX + 30
#define OBJ_EVENT_GFX_LYRA_MACH_BIKE          		COSTUME_GFX + 31
#define OBJ_EVENT_GFX_LYRA_ACRO_BIKE          		COSTUME_GFX + 32
#define OBJ_EVENT_GFX_LYRA_FISHING            		COSTUME_GFX + 33
#define OBJ_EVENT_GFX_LYRA_WATERING           		COSTUME_GFX + 34
#define OBJ_EVENT_GFX_LYRA_DECORATING         		COSTUME_GFX + 35
#define OBJ_EVENT_GFX_LYRA_UNDERWATER         		COSTUME_GFX + 36

#define OBJ_EVENT_GFX_KRIS_NORMAL 					COSTUME_GFX + 37
#define OBJ_EVENT_GFX_KRIS_FIELD_MOVE         		COSTUME_GFX + 38
#define OBJ_EVENT_GFX_KRIS_SURFING            		COSTUME_GFX + 39
#define OBJ_EVENT_GFX_KRIS_MACH_BIKE          		COSTUME_GFX + 40
#define OBJ_EVENT_GFX_KRIS_ACRO_BIKE          		COSTUME_GFX + 41
#define OBJ_EVENT_GFX_KRIS_FISHING            		COSTUME_GFX + 42
#define OBJ_EVENT_GFX_KRIS_WATERING           		COSTUME_GFX + 43
#define OBJ_EVENT_GFX_KRIS_DECORATING         		COSTUME_GFX + 44
#define OBJ_EVENT_GFX_KRIS_UNDERWATER         		COSTUME_GFX + 45

#define OBJ_EVENT_GFX_LUCAS_NORMAL 					COSTUME_GFX + 46
#define OBJ_EVENT_GFX_LUCAS_FIELD_MOVE         		COSTUME_GFX + 47
#define OBJ_EVENT_GFX_LUCAS_SURFING            		COSTUME_GFX + 48
#define OBJ_EVENT_GFX_LUCAS_MACH_BIKE          		COSTUME_GFX + 49
#define OBJ_EVENT_GFX_LUCAS_ACRO_BIKE          		COSTUME_GFX + 50
#define OBJ_EVENT_GFX_LUCAS_FISHING            		COSTUME_GFX + 51
#define OBJ_EVENT_GFX_LUCAS_WATERING           		COSTUME_GFX + 52
#define OBJ_EVENT_GFX_LUCAS_DECORATING         		COSTUME_GFX + 53
#define OBJ_EVENT_GFX_LUCAS_UNDERWATER         		COSTUME_GFX + 54

#define OBJ_EVENT_GFX_DAWN_NORMAL 					COSTUME_GFX + 55
#define OBJ_EVENT_GFX_DAWN_FIELD_MOVE         		COSTUME_GFX + 56
#define OBJ_EVENT_GFX_DAWN_SURFING            		COSTUME_GFX + 57
#define OBJ_EVENT_GFX_DAWN_MACH_BIKE          		COSTUME_GFX + 58
#define OBJ_EVENT_GFX_DAWN_ACRO_BIKE          		COSTUME_GFX + 59
#define OBJ_EVENT_GFX_DAWN_FISHING            		COSTUME_GFX + 60
#define OBJ_EVENT_GFX_DAWN_WATERING           		COSTUME_GFX + 61
#define OBJ_EVENT_GFX_DAWN_DECORATING         		COSTUME_GFX + 62
#define OBJ_EVENT_GFX_DAWN_UNDERWATER         		COSTUME_GFX + 63

#define OBJ_EVENT_GFX_LUCAS_PLATINUM_NORMAL 		COSTUME_GFX + 64
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_FIELD_MOVE 	COSTUME_GFX + 65
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_SURFING    	COSTUME_GFX + 66
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_MACH_BIKE  	COSTUME_GFX + 67
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_ACRO_BIKE  	COSTUME_GFX + 68
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_FISHING    	COSTUME_GFX + 69
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_WATERING   	COSTUME_GFX + 70
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_DECORATING 	COSTUME_GFX + 71
#define OBJ_EVENT_GFX_LUCAS_PLATINUM_UNDERWATER 	COSTUME_GFX + 72

#define OBJ_EVENT_GFX_DAWN_PLATINUM_NORMAL 			COSTUME_GFX + 73
#define OBJ_EVENT_GFX_DAWN_PLATINUM_FIELD_MOVE  	COSTUME_GFX + 74
#define OBJ_EVENT_GFX_DAWN_PLATINUM_SURFING     	COSTUME_GFX + 75
#define OBJ_EVENT_GFX_DAWN_PLATINUM_MACH_BIKE   	COSTUME_GFX + 76
#define OBJ_EVENT_GFX_DAWN_PLATINUM_ACRO_BIKE   	COSTUME_GFX + 77
#define OBJ_EVENT_GFX_DAWN_PLATINUM_FISHING     	COSTUME_GFX + 78
#define OBJ_EVENT_GFX_DAWN_PLATINUM_WATERING    	COSTUME_GFX + 79
#define OBJ_EVENT_GFX_DAWN_PLATINUM_DECORATING  	COSTUME_GFX + 80
#define OBJ_EVENT_GFX_DAWN_PLATINUM_UNDERWATER  	COSTUME_GFX + 81

#define	NPC_GFX										OBJ_EVENT_GFX_DAWN_PLATINUM_UNDERWATER

//Frontier Brains
#define OBJ_EVENT_GFX_ANABEL                      	NPC_GFX + 1
#define OBJ_EVENT_GFX_TUCKER                      	NPC_GFX + 2
#define OBJ_EVENT_GFX_GRETA                       	NPC_GFX + 3
#define OBJ_EVENT_GFX_SPENSER                     	NPC_GFX + 4
#define OBJ_EVENT_GFX_NOLAND                      	NPC_GFX + 5
#define OBJ_EVENT_GFX_LUCY                        	NPC_GFX + 6
#define OBJ_EVENT_GFX_BRANDON                    	NPC_GFX + 7

//Hoenn Gym Leaders
#define OBJ_EVENT_GFX_ROXANNE                    	NPC_GFX + 8
#define OBJ_EVENT_GFX_BRAWLY                     	NPC_GFX + 9
#define OBJ_EVENT_GFX_WATTSON                    	NPC_GFX + 10
#define OBJ_EVENT_GFX_FLANNERY                   	NPC_GFX + 11
#define OBJ_EVENT_GFX_NORMAN                     	NPC_GFX + 12
#define OBJ_EVENT_GFX_WINONA                     	NPC_GFX + 13
#define OBJ_EVENT_GFX_LIZA                       	NPC_GFX + 14
#define OBJ_EVENT_GFX_TATE                       	NPC_GFX + 15
#define OBJ_EVENT_GFX_JUAN                       	NPC_GFX + 16

//Hoenn Elite 4 & Champions
#define OBJ_EVENT_GFX_SIDNEY                     	NPC_GFX + 17
#define OBJ_EVENT_GFX_PHOEBE                     	NPC_GFX + 18
#define OBJ_EVENT_GFX_GLACIA                     	NPC_GFX + 19
#define OBJ_EVENT_GFX_DRAKE                      	NPC_GFX + 20
#define OBJ_EVENT_GFX_WALLACE                    	NPC_GFX + 21

//Evil Teams
#define OBJ_EVENT_GFX_ARCHIE                     	NPC_GFX + 22
#define OBJ_EVENT_GFX_MAXIE                      	NPC_GFX + 23
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              	NPC_GFX + 24
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              	NPC_GFX + 25
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             	NPC_GFX + 26
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             	NPC_GFX + 27
#define OBJ_EVENT_GFX_GIOVANNI             			NPC_GFX + 28 	
#define OBJ_EVENT_GFX_ROCKET_ADMIN             		NPC_GFX + 29 	
#define OBJ_EVENT_GFX_ROCKET_MEMBER_M             	NPC_GFX + 30 	
#define OBJ_EVENT_GFX_ROCKET_MEMBER_F             	NPC_GFX + 31 	
#define OBJ_EVENT_GFX_JESSIE              			NPC_GFX + 32	
#define OBJ_EVENT_GFX_JAMES	             			NPC_GFX + 33

//Unique NPCs
#define OBJ_EVENT_GFX_MOM                        	NPC_GFX + 34
#define OBJ_EVENT_GFX_PROF_BIRCH                  	NPC_GFX + 35
#define OBJ_EVENT_GFX_PROF_OAK                  	NPC_GFX + 36 
#define OBJ_EVENT_GFX_LANETTE                  		NPC_GFX + 37 
#define OBJ_EVENT_GFX_ZINNIA                  		NPC_GFX + 38 
#define OBJ_EVENT_GFX_SCOTT                      	NPC_GFX + 39
#define OBJ_EVENT_GFX_STEVEN                     	NPC_GFX + 40
#define OBJ_EVENT_GFX_WALLY                      	NPC_GFX + 41
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             	NPC_GFX + 42
#define OBJ_EVENT_GFX_NURSE                       	NPC_GFX + 43
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           	NPC_GFX + 44
#define OBJ_EVENT_GFX_MART_EMPLOYEE               	NPC_GFX + 45
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          	NPC_GFX + 46
#define OBJ_EVENT_GFX_TEALA                       	NPC_GFX + 47
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           	NPC_GFX + 48
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           	NPC_GFX + 49
#define OBJ_EVENT_GFX_GAMEBOY_KID                	NPC_GFX + 50
#define OBJ_EVENT_GFX_CONTEST_JUDGE              	NPC_GFX + 51
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      	NPC_GFX + 52
#define OBJ_EVENT_GFX_BARD                        	NPC_GFX + 53
#define OBJ_EVENT_GFX_RED                        	NPC_GFX + 54
#define OBJ_EVENT_GFX_BLUE                       	NPC_GFX + 55
#define OBJ_EVENT_GFX_LEAF                       	NPC_GFX + 56
#define OBJ_EVENT_GFX_OFFICER_JENNY                 NPC_GFX + 57
#define OBJ_EVENT_GFX_LOOKER                 		NPC_GFX + 58


//Kanto Elite Four
#define OBJ_EVENT_GFX_LORELEI                 		NPC_GFX + 59
#define OBJ_EVENT_GFX_BRUNO                			NPC_GFX + 60
#define OBJ_EVENT_GFX_AGATHA                 		NPC_GFX + 61
#define OBJ_EVENT_GFX_LANCE                 		NPC_GFX + 62

//Kanto Gym Leaders
#define OBJ_EVENT_GFX_BROCK                 		NPC_GFX + 63
#define OBJ_EVENT_GFX_MISTY                 		NPC_GFX + 64
#define OBJ_EVENT_GFX_SURGE                 		NPC_GFX + 65
#define OBJ_EVENT_GFX_ERIKA                 		NPC_GFX + 66
#define OBJ_EVENT_GFX_SABRINA                 		NPC_GFX + 67
#define OBJ_EVENT_GFX_KOGA                 			NPC_GFX + 68
#define OBJ_EVENT_GFX_BLAINE                 		NPC_GFX + 69

//MISC
#define OBJ_EVENT_GFX_LITTLE_BOY_3               	NPC_GFX + 70 //UNUSED?
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 	NPC_GFX + 71

#define GENERIC_NPC_GFX								OBJ_EVENT_GFX_QUINTY_PLUMP

//Generic NPCs
#define OBJ_EVENT_GFX_BOY_1                        	GENERIC_NPC_GFX + 1
#define OBJ_EVENT_GFX_BOY_2                        	GENERIC_NPC_GFX + 2
#define OBJ_EVENT_GFX_BOY_3                       	GENERIC_NPC_GFX + 3

#define OBJ_EVENT_GFX_GIRL_1                       	GENERIC_NPC_GFX + 4
#define OBJ_EVENT_GFX_GIRL_2                      	GENERIC_NPC_GFX + 5
#define OBJ_EVENT_GFX_GIRL_3                      	GENERIC_NPC_GFX + 6

#define OBJ_EVENT_GFX_WOMAN_1                    	GENERIC_NPC_GFX + 7
#define OBJ_EVENT_GFX_WOMAN_2                     	GENERIC_NPC_GFX + 8
#define OBJ_EVENT_GFX_WOMAN_3                     	GENERIC_NPC_GFX + 9
#define OBJ_EVENT_GFX_WOMAN_4                     	GENERIC_NPC_GFX + 10
#define OBJ_EVENT_GFX_WOMAN_5                   	GENERIC_NPC_GFX + 11

#define OBJ_EVENT_GFX_MAN_1                       	GENERIC_NPC_GFX + 12
#define OBJ_EVENT_GFX_MAN_2                       	GENERIC_NPC_GFX + 13
#define OBJ_EVENT_GFX_MAN_3                       	GENERIC_NPC_GFX + 14
#define OBJ_EVENT_GFX_MAN_4                       	GENERIC_NPC_GFX + 15
#define OBJ_EVENT_GFX_MAN_5                       	GENERIC_NPC_GFX + 16

#define GENDERED_NPC_GFX							OBJ_EVENT_GFX_MAN_5

//Gendered Pairs
#define OBJ_EVENT_GFX_EXPERT_M                    	GENDERED_NPC_GFX + 1
#define OBJ_EVENT_GFX_EXPERT_F                    	GENDERED_NPC_GFX + 2
#define OBJ_EVENT_GFX_POKEFAN_M                   	GENDERED_NPC_GFX + 3
#define OBJ_EVENT_GFX_POKEFAN_F                   	GENDERED_NPC_GFX + 4
#define OBJ_EVENT_GFX_LITTLE_BOY                  	GENDERED_NPC_GFX + 5
#define OBJ_EVENT_GFX_LITTLE_GIRL                 	GENDERED_NPC_GFX + 6
#define OBJ_EVENT_GFX_OLD_MAN                     	GENDERED_NPC_GFX + 7
#define OBJ_EVENT_GFX_OLD_WOMAN                   	GENDERED_NPC_GFX + 8
#define OBJ_EVENT_GFX_SWIMMER_M                   	GENDERED_NPC_GFX + 9
#define OBJ_EVENT_GFX_SWIMMER_F                   	GENDERED_NPC_GFX + 10
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        	GENDERED_NPC_GFX + 11
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        	GENDERED_NPC_GFX + 12
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        	GENDERED_NPC_GFX + 13
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        	GENDERED_NPC_GFX + 14
#define OBJ_EVENT_GFX_TUBER_M                     	GENDERED_NPC_GFX + 15
#define OBJ_EVENT_GFX_TUBER_F                     	GENDERED_NPC_GFX + 16
#define OBJ_EVENT_GFX_SCIENTIST_1                 	GENDERED_NPC_GFX + 17 //SCIENTIST_M
#define OBJ_EVENT_GFX_SCIENTIST_2                	GENDERED_NPC_GFX + 18 //SCIENTIST_F
#define OBJ_EVENT_GFX_REPORTER_M                  	GENDERED_NPC_GFX + 19
#define OBJ_EVENT_GFX_REPORTER_F                  	GENDERED_NPC_GFX + 20
#define OBJ_EVENT_GFX_PSYCHIC_M                   	GENDERED_NPC_GFX + 21
#define OBJ_EVENT_GFX_PSYCHIC_F                   	GENDERED_NPC_GFX + 22 
#define OBJ_EVENT_GFX_SCHOOL_KID_M                	GENDERED_NPC_GFX + 23
#define OBJ_EVENT_GFX_SCHOOL_KID_F                	GENDERED_NPC_GFX + 24 
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           	GENDERED_NPC_GFX + 25
#define OBJ_EVENT_GFX_TUBER_F_SWIMMING           	GENDERED_NPC_GFX + 26
#define OBJ_EVENT_GFX_BREEDER_M                		GENDERED_NPC_GFX + 27
#define OBJ_EVENT_GFX_BREEDER_F                		GENDERED_NPC_GFX + 28 
#define OBJ_EVENT_GFX_COOL_TRAINER_M                GENDERED_NPC_GFX + 29
#define OBJ_EVENT_GFX_COOL_TRAINER_F                GENDERED_NPC_GFX + 30 

#define TRAINER_NPC_GFX								OBJ_EVENT_GFX_COOL_TRAINER_F

//Trainer Classes
#define OBJ_EVENT_GFX_HIKER                       	TRAINER_NPC_GFX + 1
#define OBJ_EVENT_GFX_BLACK_BELT                  	TRAINER_NPC_GFX + 2
#define OBJ_EVENT_GFX_BEAUTY                      	TRAINER_NPC_GFX + 3
#define OBJ_EVENT_GFX_LASS                        	TRAINER_NPC_GFX + 4
#define OBJ_EVENT_GFX_GENTLEMAN                   	TRAINER_NPC_GFX + 5
#define OBJ_EVENT_GFX_SAILOR                      	TRAINER_NPC_GFX + 6
#define OBJ_EVENT_GFX_FISHERMAN                   	TRAINER_NPC_GFX + 7
#define OBJ_EVENT_GFX_ARTIST                      	TRAINER_NPC_GFX + 8
#define OBJ_EVENT_GFX_CAMERAMAN                  	TRAINER_NPC_GFX + 9
#define OBJ_EVENT_GFX_NINJA_BOY                   	TRAINER_NPC_GFX + 10
#define OBJ_EVENT_GFX_TWIN                         	TRAINER_NPC_GFX + 11
#define OBJ_EVENT_GFX_RICH_BOY                    	TRAINER_NPC_GFX + 12
#define OBJ_EVENT_GFX_FAT_MAN                     	TRAINER_NPC_GFX + 13
#define OBJ_EVENT_GFX_COOK                        	TRAINER_NPC_GFX + 14
#define OBJ_EVENT_GFX_YOUNGSTER                   	TRAINER_NPC_GFX + 15
#define OBJ_EVENT_GFX_BUG_CATCHER                 	TRAINER_NPC_GFX + 16
#define OBJ_EVENT_GFX_MANIAC                      	TRAINER_NPC_GFX + 17
#define OBJ_EVENT_GFX_HEX_MANIAC                  	TRAINER_NPC_GFX + 18
#define OBJ_EVENT_GFX_CAMPER                      	TRAINER_NPC_GFX + 19
#define OBJ_EVENT_GFX_PICNICKER                   	TRAINER_NPC_GFX + 20

#define OVERWORLD_POKEMON_GFX						OBJ_EVENT_GFX_PICNICKER

//Overworld Pokemon
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              	OVERWORLD_POKEMON_GFX + 1
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              	OVERWORLD_POKEMON_GFX + 2
#define OBJ_EVENT_GFX_KYOGRE_FRONT               	OVERWORLD_POKEMON_GFX + 3
#define OBJ_EVENT_GFX_KYOGRE_SIDE                	OVERWORLD_POKEMON_GFX + 4
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             	OVERWORLD_POKEMON_GFX + 5
#define OBJ_EVENT_GFX_GROUDON_FRONT              	OVERWORLD_POKEMON_GFX + 6
#define OBJ_EVENT_GFX_GROUDON_SIDE               	OVERWORLD_POKEMON_GFX + 7
#define OBJ_EVENT_GFX_PIKACHU                    	OVERWORLD_POKEMON_GFX + 8
#define OBJ_EVENT_GFX_AZURILL                    	OVERWORLD_POKEMON_GFX + 9
#define OBJ_EVENT_GFX_AZUMARILL                  	OVERWORLD_POKEMON_GFX + 10
#define OBJ_EVENT_GFX_SKITTY                     	OVERWORLD_POKEMON_GFX + 11
#define OBJ_EVENT_GFX_KECLEON                    	OVERWORLD_POKEMON_GFX + 12
#define OBJ_EVENT_GFX_KIRLIA                     	OVERWORLD_POKEMON_GFX + 13
#define OBJ_EVENT_GFX_DUSCLOPS                   	OVERWORLD_POKEMON_GFX + 14
#define OBJ_EVENT_GFX_SUDOWOODO                  	OVERWORLD_POKEMON_GFX + 15
#define OBJ_EVENT_GFX_POOCHYENA                  	OVERWORLD_POKEMON_GFX + 16
#define OBJ_EVENT_GFX_WINGULL                    	OVERWORLD_POKEMON_GFX + 17
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 	OVERWORLD_POKEMON_GFX + 18
#define OBJ_EVENT_GFX_ZIGZAGOON_2                	OVERWORLD_POKEMON_GFX + 19
#define OBJ_EVENT_GFX_MEW                        	OVERWORLD_POKEMON_GFX + 20
#define OBJ_EVENT_GFX_DEOXYS                     	OVERWORLD_POKEMON_GFX + 21
#define OBJ_EVENT_GFX_LUGIA                      	OVERWORLD_POKEMON_GFX + 22
#define OBJ_EVENT_GFX_HOOH                       	OVERWORLD_POKEMON_GFX + 23
#define OBJ_EVENT_GFX_LATIAS                     	OVERWORLD_POKEMON_GFX + 24
#define OBJ_EVENT_GFX_LATIOS                     	OVERWORLD_POKEMON_GFX + 25
#define OBJ_EVENT_GFX_REGIROCK                   	OVERWORLD_POKEMON_GFX + 26
#define OBJ_EVENT_GFX_REGICE                     	OVERWORLD_POKEMON_GFX + 27
#define OBJ_EVENT_GFX_REGISTEEL                  	OVERWORLD_POKEMON_GFX + 28
#define OBJ_EVENT_GFX_SNORLAX_SLEEPING              OVERWORLD_POKEMON_GFX + 29
#define OBJ_EVENT_GFX_SPEAROW              			OVERWORLD_POKEMON_GFX + 30
#define OBJ_EVENT_GFX_JIGGLYPUFF              		OVERWORLD_POKEMON_GFX + 31
#define OBJ_EVENT_GFX_NIDORAN_M						OVERWORLD_POKEMON_GFX + 32
#define OBJ_EVENT_GFX_RAYQUAZA                   	OVERWORLD_POKEMON_GFX + 33

#define DECORATION_GFX							OBJ_EVENT_GFX_RAYQUAZA

#define OBJ_EVENT_GFX_PICHU_DOLL                DECORATION_GFX + 1
#define OBJ_EVENT_GFX_PIKACHU_DOLL              DECORATION_GFX + 2
#define OBJ_EVENT_GFX_MARILL_DOLL               DECORATION_GFX + 3
#define OBJ_EVENT_GFX_TOGEPI_DOLL               DECORATION_GFX + 4
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL            DECORATION_GFX + 5
#define OBJ_EVENT_GFX_CHIKORITA_DOLL            DECORATION_GFX + 6
#define OBJ_EVENT_GFX_TOTODILE_DOLL             DECORATION_GFX + 7
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL           DECORATION_GFX + 8
#define OBJ_EVENT_GFX_MEOWTH_DOLL               DECORATION_GFX + 9
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL             DECORATION_GFX + 10
#define OBJ_EVENT_GFX_DITTO_DOLL                DECORATION_GFX + 11
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL             DECORATION_GFX + 12
#define OBJ_EVENT_GFX_TREECKO_DOLL              DECORATION_GFX + 13
#define OBJ_EVENT_GFX_TORCHIC_DOLL              DECORATION_GFX + 14
#define OBJ_EVENT_GFX_MUDKIP_DOLL               DECORATION_GFX + 15
#define OBJ_EVENT_GFX_DUSKULL_DOLL              DECORATION_GFX + 16
#define OBJ_EVENT_GFX_WYNAUT_DOLL               DECORATION_GFX + 17
#define OBJ_EVENT_GFX_BALTOY_DOLL               DECORATION_GFX + 18
#define OBJ_EVENT_GFX_KECLEON_DOLL              DECORATION_GFX + 19
#define OBJ_EVENT_GFX_AZURILL_DOLL              DECORATION_GFX + 20
#define OBJ_EVENT_GFX_SKITTY_DOLL               DECORATION_GFX + 21
#define OBJ_EVENT_GFX_SWABLU_DOLL               DECORATION_GFX + 22
#define OBJ_EVENT_GFX_GULPIN_DOLL               DECORATION_GFX + 23
#define OBJ_EVENT_GFX_LOTAD_DOLL                DECORATION_GFX + 24
#define OBJ_EVENT_GFX_SEEDOT_DOLL               DECORATION_GFX + 25
#define OBJ_EVENT_GFX_PIKA_CUSHION              DECORATION_GFX + 26
#define OBJ_EVENT_GFX_ROUND_CUSHION             DECORATION_GFX + 27
#define OBJ_EVENT_GFX_KISS_CUSHION              DECORATION_GFX + 28
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION            DECORATION_GFX + 29
#define OBJ_EVENT_GFX_SPIN_CUSHION              DECORATION_GFX + 30
#define OBJ_EVENT_GFX_DIAMOND_CUSHION           DECORATION_GFX + 31
#define OBJ_EVENT_GFX_BALL_CUSHION              DECORATION_GFX + 32
#define OBJ_EVENT_GFX_GRASS_CUSHION             DECORATION_GFX + 33
#define OBJ_EVENT_GFX_FIRE_CUSHION              DECORATION_GFX + 34
#define OBJ_EVENT_GFX_WATER_CUSHION             DECORATION_GFX + 35
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL          DECORATION_GFX + 36
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL           DECORATION_GFX + 37
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL           DECORATION_GFX + 38
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL         DECORATION_GFX + 39
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL        DECORATION_GFX + 40
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL        DECORATION_GFX + 41
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL          DECORATION_GFX + 42
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL         DECORATION_GFX + 43
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL           DECORATION_GFX + 44
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL        DECORATION_GFX + 45
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL          DECORATION_GFX + 46
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL     DECORATION_GFX + 47
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL      DECORATION_GFX + 48
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL        DECORATION_GFX + 49
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL       DECORATION_GFX + 50
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL      DECORATION_GFX + 51

#define NUM_OBJ_EVENT_GFX						DECORATION_GFX + 52 

// NOTE: By default, the max value for NUM_OBJ_EVENT_GFX is 239.
//
// Object event graphics ids are 1 byte in size (max value of 255), and the dynamic
// graphics ids that start after NUM_OBJ_EVENT_GFX reach this limit. No graphics id
// uses the value 239 itself, so removing the "+ 1" in OBJ_EVENT_GFX_VARS would
// allow increasing NUM_OBJ_EVENT_GFX to 240. There are also a handful of unused
// object graphics that can be removed. If more graphics are needed, anything that
// stores graphics ids will need to be increased in size. See wiki entry below:
// https://github.com/pret/pokeemerald/wiki/Feature-Branches#overworld-expansion

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3 // unused; repurposed to mean no shadow
#define SHADOW_SIZE_NONE 3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F
#define OBJ_EVENT_ID_FOLLOWER 0xFE

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
