#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 1
#define HEAL_LOCATION_PALLET_TOWN 2
#define HEAL_LOCATION_PLAYERS_HOUSE 3
#define HEAL_LOCATION_VIRIDIAN_CITY 4
#define HEAL_LOCATION_PEWTER_CITY 5
#define HEAL_LOCATION_CERULEAN_CITY 6
#define HEAL_LOCATION_VERMILION_CITY 7
#define HEAL_LOCATION_CELADON_CITY 8
#define HEAL_LOCATION_SAFFRON_CITY 9
#define HEAL_LOCATION_FUCHSIA_CITY 10
#define HEAL_LOCATION_CINNABAR_ISLAND 11
#define HEAL_LOCATION_LAVENDER_TOWN 12
#define HEAL_LOCATION_ROUTE_4 13
#define HEAL_LOCATION_ROUTE_10 14
#define HEAL_LOCATION_INDIGO_PLATEAU 15
#define HEAL_LOCATION_BATTLE_TOWER_EXTERIOR 16

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
