#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY          (0 | (0 << 8))
#define MAP_SLATEPORT_CITY          (1 | (0 << 8))
#define MAP_MAUVILLE_CITY           (2 | (0 << 8))
#define MAP_RUSTBORO_CITY           (3 | (0 << 8))
#define MAP_FORTREE_CITY            (4 | (0 << 8))
#define MAP_LILYCOVE_CITY           (5 | (0 << 8))
#define MAP_MOSSDEEP_CITY           (6 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY         (7 | (0 << 8))
#define MAP_EVER_GRANDE_CITY        (8 | (0 << 8))
#define MAP_LITTLEROOT_TOWN         (9 | (0 << 8))
#define MAP_OLDALE_TOWN             (10 | (0 << 8))
#define MAP_DEWFORD_TOWN            (11 | (0 << 8))
#define MAP_LAVARIDGE_TOWN          (12 | (0 << 8))
#define MAP_FALLARBOR_TOWN          (13 | (0 << 8))
#define MAP_VERDANTURF_TOWN         (14 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN         (15 | (0 << 8))
#define MAP_ROUTE101                (16 | (0 << 8))
#define MAP_ROUTE102                (17 | (0 << 8))
#define MAP_ROUTE103                (18 | (0 << 8))
#define MAP_ROUTE104                (19 | (0 << 8))
#define MAP_ROUTE105                (20 | (0 << 8))
#define MAP_ROUTE106                (21 | (0 << 8))
#define MAP_ROUTE107                (22 | (0 << 8))
#define MAP_ROUTE108                (23 | (0 << 8))
#define MAP_ROUTE109                (24 | (0 << 8))
#define MAP_ROUTE110                (25 | (0 << 8))
#define MAP_ROUTE111                (26 | (0 << 8))
#define MAP_ROUTE112                (27 | (0 << 8))
#define MAP_ROUTE113                (28 | (0 << 8))
#define MAP_ROUTE114                (29 | (0 << 8))
#define MAP_ROUTE115                (30 | (0 << 8))
#define MAP_ROUTE116                (31 | (0 << 8))
#define MAP_ROUTE117                (32 | (0 << 8))
#define MAP_ROUTE118                (33 | (0 << 8))
#define MAP_ROUTE119                (34 | (0 << 8))
#define MAP_ROUTE120                (35 | (0 << 8))
#define MAP_ROUTE121                (36 | (0 << 8))
#define MAP_ROUTE122                (37 | (0 << 8))
#define MAP_ROUTE123                (38 | (0 << 8))
#define MAP_ROUTE124                (39 | (0 << 8))
#define MAP_ROUTE125                (40 | (0 << 8))
#define MAP_ROUTE126                (41 | (0 << 8))
#define MAP_ROUTE127                (42 | (0 << 8))
#define MAP_ROUTE128                (43 | (0 << 8))
#define MAP_ROUTE129                (44 | (0 << 8))
#define MAP_ROUTE130                (45 | (0 << 8))
#define MAP_ROUTE131                (46 | (0 << 8))
#define MAP_ROUTE132                (47 | (0 << 8))
#define MAP_ROUTE133                (48 | (0 << 8))
#define MAP_ROUTE134                (49 | (0 << 8))
#define MAP_UNDERWATER_ROUTE124     (50 | (0 << 8))
#define MAP_UNDERWATER_ROUTE126     (51 | (0 << 8))
#define MAP_UNDERWATER_ROUTE127     (52 | (0 << 8))
#define MAP_UNDERWATER_ROUTE128     (53 | (0 << 8))
#define MAP_UNDERWATER_ROUTE129     (54 | (0 << 8))
#define MAP_UNDERWATER_ROUTE105     (55 | (0 << 8))
#define MAP_UNDERWATER_ROUTE125     (56 | (0 << 8))
#define MAP_PALLET_TOWN             (57 | (0 << 8))
#define MAP_VIRIDIAN_CITY           (58 | (0 << 8))
#define MAP_PEWTER_CITY             (59 | (0 << 8))
#define MAP_CERULEAN_CITY           (60 | (0 << 8))
#define MAP_LAVENDER_TOWN           (61 | (0 << 8))
#define MAP_VERMILION_CITY          (62 | (0 << 8))
#define MAP_CELADON_CITY            (63 | (0 << 8))
#define MAP_FUCHSIA_CITY            (64 | (0 << 8))
#define MAP_CINNABAR_ISLAND         (65 | (0 << 8))
#define MAP_SAFFRON_CITY            (66 | (0 << 8))
#define MAP_ROUTE1                  (67 | (0 << 8))
#define MAP_ROUTE2                  (68 | (0 << 8))
#define MAP_ROUTE3                  (69 | (0 << 8))
#define MAP_ROUTE4                  (70 | (0 << 8))
#define MAP_ROUTE5                  (71 | (0 << 8))
#define MAP_ROUTE6                  (72 | (0 << 8))
#define MAP_ROUTE7                  (73 | (0 << 8))
#define MAP_ROUTE8                  (74 | (0 << 8))
#define MAP_ROUTE9                  (75 | (0 << 8))
#define MAP_ROUTE10                 (76 | (0 << 8))
#define MAP_ROUTE11                 (77 | (0 << 8))
#define MAP_ROUTE12                 (78 | (0 << 8))
#define MAP_ROUTE13                 (79 | (0 << 8))
#define MAP_ROUTE14                 (80 | (0 << 8))
#define MAP_ROUTE15                 (81 | (0 << 8))
#define MAP_ROUTE16                 (82 | (0 << 8))
#define MAP_ROUTE17                 (83 | (0 << 8))
#define MAP_ROUTE18                 (84 | (0 << 8))
#define MAP_ROUTE19                 (85 | (0 << 8))
#define MAP_ROUTE20                 (86 | (0 << 8))
#define MAP_ROUTE21_NORTH           (87 | (0 << 8))
#define MAP_ROUTE21_SOUTH           (88 | (0 << 8))
#define MAP_ROUTE22                 (89 | (0 << 8))
#define MAP_ROUTE23                 (90 | (0 << 8))
#define MAP_ROUTE24                 (91 | (0 << 8))
#define MAP_ROUTE25                 (92 | (0 << 8))
#define MAP_INDIGO_PLATEAU_EXTERIOR (93 | (0 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (1 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (3 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (3 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (3 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (3 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (3 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (4 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (4 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (5 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (5 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (5 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (6 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (6 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (6 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (6 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (6 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (7 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (8 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (8 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (8 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (9 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (9 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (9 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (9 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (9 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (9 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (9 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (9 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (9 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (10 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (10 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (10 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (10 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (11 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (11 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (11 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (11 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (12 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (12 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (12 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (12 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (13 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (13 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (13 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (13 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (13 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (14 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (14 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (14 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (15 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (15 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (16 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (17 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (17 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (18 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (18 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (19 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (19 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (20 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (20 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (20 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (21 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (22 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (23 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (24 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (24 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (24 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (24 << 8))
#define MAP_DESERT_RUINS                             (6 | (24 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (24 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (24 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (24 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (24 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (24 << 8))
#define MAP_MT_CHIMNEY                               (12 | (24 << 8))
#define MAP_JAGGED_PASS                              (13 | (24 << 8))
#define MAP_FIERY_PATH                               (14 | (24 << 8))
#define MAP_MT_PYRE_1F                               (15 | (24 << 8))
#define MAP_MT_PYRE_2F                               (16 | (24 << 8))
#define MAP_MT_PYRE_3F                               (17 | (24 << 8))
#define MAP_MT_PYRE_4F                               (18 | (24 << 8))
#define MAP_MT_PYRE_5F                               (19 | (24 << 8))
#define MAP_MT_PYRE_6F                               (20 | (24 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (21 | (24 << 8))
#define MAP_MT_PYRE_SUMMIT                           (22 | (24 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (23 | (24 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (24 | (24 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (25 | (24 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (26 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (27 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (28 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (29 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (30 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (31 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (32 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (33 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (34 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (35 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (36 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (37 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (38 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (39 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (40 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (41 | (24 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (42 | (24 << 8))
#define MAP_VICTORY_ROAD_1F                          (43 | (24 << 8))
#define MAP_VICTORY_ROAD_B1F                         (44 | (24 << 8))
#define MAP_VICTORY_ROAD_B2F                         (45 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (46 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (47 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (48 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (49 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (50 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (51 | (24 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (52 | (24 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (53 | (24 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (54 | (24 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (55 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (56 | (24 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (57 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (58 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (59 | (24 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (60 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (61 | (24 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (62 | (24 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (63 | (24 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (64 | (24 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (65 | (24 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (66 | (24 << 8))
#define MAP_ISLAND_CAVE                              (67 | (24 << 8))
#define MAP_ANCIENT_TOMB                             (68 | (24 << 8))
#define MAP_UNDERWATER_ROUTE134                      (69 | (24 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (70 | (24 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (71 | (24 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (72 | (24 << 8))
#define MAP_SCORCHED_SLAB                            (73 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (74 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (75 | (24 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (76 | (24 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (77 | (24 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (78 | (24 << 8))
#define MAP_SKY_PILLAR_1F                            (79 | (24 << 8))
#define MAP_SKY_PILLAR_2F                            (80 | (24 << 8))
#define MAP_SKY_PILLAR_3F                            (81 | (24 << 8))
#define MAP_SKY_PILLAR_4F                            (82 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (83 | (24 << 8))
#define MAP_SKY_PILLAR_5F                            (84 | (24 << 8))
#define MAP_SKY_PILLAR_TOP                           (85 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (86 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (87 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (88 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (89 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (90 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (91 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (92 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (93 | (24 << 8))
#define MAP_MIRAGE_TOWER_1F                          (94 | (24 << 8))
#define MAP_MIRAGE_TOWER_2F                          (95 | (24 << 8))
#define MAP_MIRAGE_TOWER_3F                          (96 | (24 << 8))
#define MAP_MIRAGE_TOWER_4F                          (97 | (24 << 8))
#define MAP_DESERT_UNDERPASS                         (98 | (24 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (99 | (24 << 8))
#define MAP_ARTISAN_CAVE_1F                          (100 | (24 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (101 | (24 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (102 | (24 << 8))
#define MAP_MARINE_CAVE_END                          (103 | (24 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (104 | (24 << 8))
#define MAP_TERRA_CAVE_END                           (105 | (24 << 8))
#define MAP_ALTERING_CAVE                            (106 | (24 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (107 | (24 << 8))
#define MAP_VIRIDIAN_FOREST                          (108 | (24 << 8))
#define MAP_MT_MOON_1F                               (109 | (24 << 8))
#define MAP_MT_MOON_B1F                              (110 | (24 << 8))
#define MAP_MT_MOON_B2F                              (111 | (24 << 8))
#define MAP_SSANNE_EXTERIOR                          (112 | (24 << 8))
#define MAP_SSANNE_1F_CORRIDOR                       (113 | (24 << 8))
#define MAP_SSANNE_2F_CORRIDOR                       (114 | (24 << 8))
#define MAP_SSANNE_3F_CORRIDOR                       (115 | (24 << 8))
#define MAP_SSANNE_B1F_CORRIDOR                      (116 | (24 << 8))
#define MAP_SSANNE_DECK                              (117 | (24 << 8))
#define MAP_SSANNE_KITCHEN                           (118 | (24 << 8))
#define MAP_SSANNE_CAPTAINS_OFFICE                   (119 | (24 << 8))
#define MAP_SSANNE_1F_ROOM1                          (120 | (24 << 8))
#define MAP_SSANNE_1F_ROOM2                          (121 | (24 << 8))
#define MAP_SSANNE_1F_ROOM3                          (122 | (24 << 8))
#define MAP_SSANNE_1F_ROOM4                          (123 | (24 << 8))
#define MAP_SSANNE_1F_ROOM5                          (124 | (24 << 8))
#define MAP_SSANNE_1F_ROOM6                          (125 | (24 << 8))
#define MAP_SSANNE_1F_ROOM7                          (126 | (24 << 8))
#define MAP_SSANNE_2F_ROOM1                          (127 | (24 << 8))
#define MAP_SSANNE_2F_ROOM2                          (128 | (24 << 8))
#define MAP_SSANNE_2F_ROOM3                          (129 | (24 << 8))
#define MAP_SSANNE_2F_ROOM4                          (130 | (24 << 8))
#define MAP_SSANNE_2F_ROOM5                          (131 | (24 << 8))
#define MAP_SSANNE_2F_ROOM6                          (132 | (24 << 8))
#define MAP_SSANNE_B1F_ROOM1                         (133 | (24 << 8))
#define MAP_SSANNE_B1F_ROOM2                         (134 | (24 << 8))
#define MAP_SSANNE_B1F_ROOM3                         (135 | (24 << 8))
#define MAP_SSANNE_B1F_ROOM4                         (136 | (24 << 8))
#define MAP_SSANNE_B1F_ROOM5                         (137 | (24 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (25 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (25 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (25 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (25 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (25 << 8))
#define MAP_TRADE_CENTER             (25 | (25 << 8))
#define MAP_RECORD_CORNER            (26 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (25 << 8))
#define MAP_CONTEST_HALL             (28 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (25 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (25 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (25 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (25 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (25 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (25 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (25 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (25 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (25 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (25 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (25 << 8))
#define MAP_UNION_ROOM               (60 | (25 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (26 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (26 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (26 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (26 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (26 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (26 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (26 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (26 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (26 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (26 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (26 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (26 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (26 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (26 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (26 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (26 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (26 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (26 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (26 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (26 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (26 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (26 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (26 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (26 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (26 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (26 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (26 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (27 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (27 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (28 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (29 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (30 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (31 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (32 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (32 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (32 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (33 << 8))

// gMapGroup_IndoorPallet
#define MAP_PALLET_TOWN_PLAYERS_HOUSE_1F   (0 | (34 << 8))
#define MAP_PALLET_TOWN_PLAYERS_HOUSE_2F   (1 | (34 << 8))
#define MAP_PALLET_TOWN_RIVALS_HOUSE       (2 | (34 << 8))
#define MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB (3 | (34 << 8))

// gMapGroup_IndoorViridian
#define MAP_VIRIDIAN_CITY_HOUSE             (0 | (35 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (1 | (35 << 8))
#define MAP_VIRIDIAN_CITY_SCHOOL            (2 | (35 << 8))
#define MAP_VIRIDIAN_CITY_MART              (3 | (35 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (4 | (35 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F (5 | (35 << 8))

// gMapGroup_IndoorPewter
#define MAP_PEWTER_CITY_MUSEUM_1F         (0 | (36 << 8))
#define MAP_PEWTER_CITY_MUSEUM_2F         (1 | (36 << 8))
#define MAP_PEWTER_CITY_GYM               (2 | (36 << 8))
#define MAP_PEWTER_CITY_MART              (3 | (36 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F (4 | (36 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F (5 | (36 << 8))
#define MAP_PEWTER_CITY_HOUSE1            (6 | (36 << 8))
#define MAP_PEWTER_CITY_HOUSE2            (7 | (36 << 8))

// gMapGroup_IndoorCerulean
#define MAP_CERULEAN_CITY_HOUSE1            (0 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (1 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (2 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE4            (3 | (37 << 8))
#define MAP_CERULEAN_CITY_HOUSE5            (4 | (37 << 8))
#define MAP_CERULEAN_CITY_GYM               (5 | (37 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP         (6 | (37 << 8))
#define MAP_CERULEAN_CITY_MART              (7 | (37 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (8 | (37 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F (9 | (37 << 8))

// gMapGroup_IndoorLavender
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F       (0 | (38 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F       (1 | (38 << 8))
#define MAP_LAVENDER_TOWN_MART                    (2 | (38 << 8))
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE (3 | (38 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1                  (4 | (38 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2                  (5 | (38 << 8))

// gMapGroup_IndoorVermilion
#define MAP_VERMILION_CITY_HOUSE1            (0 | (39 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (1 | (39 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (2 | (39 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (3 | (39 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F (4 | (39 << 8))
#define MAP_VERMILION_CITY_MART              (5 | (39 << 8))
#define MAP_VERMILION_CITY_GYM               (6 | (39 << 8))
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB  (7 | (39 << 8))

// gMapGroup_IndoorCeladon
#define MAP_CELADON_CITY_POKEMON_CENTER_1F         (0 | (40 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_2F         (1 | (40 << 8))
#define MAP_CELADON_CITY_GYM                       (2 | (40 << 8))
#define MAP_CELADON_CITY_RESTAURANT                (3 | (40 << 8))
#define MAP_CELADON_CITY_HOTEL                     (4 | (40 << 8))
#define MAP_CELADON_CITY_HOUSE1                    (5 | (40 << 8))
#define MAP_CELADON_CITY_GAME_CORNER               (6 | (40 << 8))
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM    (7 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_1F           (8 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_2F           (9 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_3F           (10 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF         (11 | (40 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM    (12 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F       (13 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F       (14 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F       (15 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F       (16 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F       (17 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOF     (18 | (40 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR (19 | (40 << 8))

// gMapGroup_IndoorFuchsia
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F    (0 | (41 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F    (1 | (41 << 8))
#define MAP_FUCHSIA_CITY_MART                 (2 | (41 << 8))
#define MAP_FUCHSIA_CITY_GYM                  (3 | (41 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1               (4 | (41 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2               (5 | (41 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3               (6 | (41 << 8))
#define MAP_FUCHSIA_CITY_WARDENS_HOUSE        (7 | (41 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE   (8 | (41 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE (9 | (41 << 8))

// gMapGroup_IndoorCinnabar
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F   (0 | (42 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F   (1 | (42 << 8))
#define MAP_CINNABAR_ISLAND_MART                (2 | (42 << 8))
#define MAP_CINNABAR_ISLAND_GYM                 (3 | (42 << 8))
#define MAP_CINNABAR_ISLAND_LAB_ENTRANCE        (4 | (42 << 8))
#define MAP_CINNABAR_ISLAND_LAB_LOUNGE          (5 | (42 << 8))
#define MAP_CINNABAR_ISLAND_LAB_RESEARCH_ROOM   (6 | (42 << 8))
#define MAP_CINNABAR_ISLAND_LAB_EXPERIMENT_ROOM (7 | (42 << 8))

// gMapGroup_IndoorSaffron
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F        (0 | (43 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F        (1 | (43 << 8))
#define MAP_SAFFRON_CITY_MART                     (2 | (43 << 8))
#define MAP_SAFFRON_CITY_GYM                      (3 | (43 << 8))
#define MAP_SAFFRON_CITY_DOJO                     (4 | (43 << 8))
#define MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE        (5 | (43 << 8))
#define MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB (6 | (43 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F        (7 | (43 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F        (8 | (43 << 8))
#define MAP_SAFFRON_CITY_HOUSE                    (9 | (43 << 8))

// gMapGroup_IndoorIndigoPlateau
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (44 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F (1 | (44 << 8))

// gMapGroup_IndoorRoute2
#define MAP_VIRIDIAN_FOREST_NORTH_ENTRANCE (0 | (45 << 8))
#define MAP_VIRIDIAN_FOREST_SOUTH_ENTRANCE (1 | (45 << 8))
#define MAP_ROUTE2_HOUSE                   (2 | (45 << 8))
#define MAP_ROUTE2_EAST_BUILDING           (3 | (45 << 8))

// gMapGroup_IndoorRoute4
#define MAP_ROUTE4_POKEMON_CENTER_1F (0 | (46 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_2F (1 | (46 << 8))

// gMapGroup_IndoorRoute5
#define MAP_ROUTE5_POKEMON_DAY_CARE (0 | (47 << 8))
#define MAP_ROUTE5_SOUTH_ENTRANCE   (1 | (47 << 8))

// gMapGroup_IndoorRoute6
#define MAP_ROUTE6_NORTH_ENTRANCE (0 | (48 << 8))

// gMapGroup_IndoorRoute7
#define MAP_ROUTE7_EAST_ENTRANCE (0 | (49 << 8))

// gMapGroup_IndoorRoute8
#define MAP_ROUTE8_WEST_ENTRANCE (0 | (50 << 8))

// gMapGroup_IndoorRoute10
#define MAP_ROUTE10_POKEMON_CENTER_1F (0 | (51 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_2F (1 | (51 << 8))

// gMapGroup_IndoorRoute11
#define MAP_ROUTE11_EAST_ENTRANCE_1F (0 | (52 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_2F (1 | (52 << 8))

// gMapGroup_IndoorRoute12
#define MAP_ROUTE12_NORTH_ENTRANCE_1F (0 | (53 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_2F (1 | (53 << 8))
#define MAP_ROUTE12_FISHING_HOUSE     (2 | (53 << 8))

// gMapGroup_IndoorRoute15
#define MAP_ROUTE15_WEST_ENTRANCE_1F (0 | (54 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_2F (1 | (54 << 8))

// gMapGroup_IndoorRoute16
#define MAP_ROUTE16_NORTH_ENTRANCE_1F (0 | (55 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_2F (1 | (55 << 8))
#define MAP_ROUTE16_HOUSE             (2 | (55 << 8))

// gMapGroup_IndoorRoute18
#define MAP_ROUTE18_EAST_ENTRANCE_1F (0 | (56 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_2F (1 | (56 << 8))

// gMapGroup_IndoorRoute22
#define MAP_ROUTE22_NORTH_ENTRANCE (0 | (57 << 8))

// gMapGroup_IndoorRoute25
#define MAP_ROUTE25_SEA_COTTAGE (0 | (58 << 8))

#define MAP_GROUPS_COUNT 59

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
