gText_Birch_Welcome::
    .string "Hello, there!\n"
    .string "Glad to meet you!\p"
    .string "Welcome to the world of Pokémon!\p"
    .string "My name is Oak.\p"
    .string "People affectionately refer to me\n"
    .string "as the Pokémon Professor.\p"
    .string "$"

gText_Birch_Pokemon::
	.string "This world…\p"
	.string "$"

gText_Birch_MainSpeech::
    .string "…is inhabited far and wide by\n"
    .string "creatures called Pokémon.\p"
    .string "For some people, Pokémon are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study Pokémon as a profession.\p"
    .string "$"

gText_Birch_AndYouAre::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
    .string "Let's begin with your name.\n"
    .string "What is it?$"

gText_Birch_SoItsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gText_Birch_ThisIsYourRival::
    .string "This is my grandson.\p"
    .string "He's been your rival since you both\n"
    .string "were babies.\p"
    .string "…Erm, what was his name now?$"

gText_Birch_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gText_Birch_YourePlayer::
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gText_Birch_AreYouReady::
    .string "{PLAYER}!\p"
    .string "Your very own Pokémon legend is\n"
    .string "about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with Pokémon awaits! Let's go!\p"
    .string "$"

