@UPDATED
MatchCall_Text_OakRegisterCall:
	.string "Oak: Oh, {PLAYER}{KUN}!\n"
	.string "I see you have a Cell Phone!\p"
	.string "Well, I should give you my number.\p"
	.string "That way, I'd be able to examine\n"
	.string "your Pokédex even while you're\l"
	.string "out in the field.$"

MatchCall_Text_RegisteredOak: 
	.string "Professor Oak registered their\n"
	.string "info in your Cell Phone.$"

MatchCall_Text_RegisteredScott:
	.string "Scott registered their info in\n"
	.string "in your Cell Phone.$"

MatchCall_Text_ScottBusy::
	.string "… beep … beep … beep …\p"
	.string "Scott's line seems to be'\n"
	.string "busy…$"

MatchCall_Text_ScottCerulean::
	.string "Scott: Hey! Champ in the making!\p"
	.string "You made it to Cerulean City!\p"
	.string "You going to challenge Misty?\n"
	.string "Better bring a swimsuit! Ha!\p"
	.string "Let's see if I was right about\n"
	.string "you. See you at the gym!$"

MatchCall_Text_ScottGotBadge2::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Congratulations on earning your\n"
	.string "Cascade Badge!\p"
	.string "You're really getting the hang of this!$"

MatchCall_Text_ScottVermilion::
	.string "Scott: Hey! Champ in the making!\p"
	.string "I heard you reached Vermilion City!\p"
	.string "Planning to take on Lt. Surge?\p"
	.string "Great! I'll be watching!$"

MatchCall_Text_ScottGotBadge3::
	.string "Scott: Hey! Champ in the making!\p"
	.string "What a match! I knew you'd be able\n"
	.string "to get that Thunder Badge!\p"
	.string "But it only gets harder from here!$"

MatchCall_Text_ScottCeladon::
	.string "Scott: Hey! Champ in the making!\p"
	.string "So you made it to Celadon City!\p"
	.string "Maybe I'll take a break from the\n"
	.string "game corner and catch your match!$"

MatchCall_Text_ScottGotBadge4::
	.string "Scott: Hey! Champ in the making!\p"
	.string "I'm glad I didn't miss that match.\n"
	.string "What a show!\p"
	.string "You're definitely making a name for\n"
	.string "for yourself!$"

MatchCall_Text_ScottSaffron::
	.string "Scott: Hey! Champ in the making!\p"
	.string "I was hoping to catch you in\n"
	.string "Saffron City, but there were all\l"
	.string "these Team Rocket grunts around!\p"
	.string "Did you know anything about that?$"

MatchCall_Text_ScottGotBadge5::
	.string "Scott: Hey! Champ in the making!\p"
	.string "If Sabrina had read my mind,\n"
	.string "she'd know I never had any doubts!\p"
	.string "Great job earning your Marsh Badge!$"

MatchCall_Text_ScottFuchsia::
	.string "Scott: Hey! Champ in the making!\p"
	.string "What's that? You're in Fuchsia?\n"
	.string "City, too?\p"
	.string "Come again?\n"
	.string "Yeah! I'm over at the Safari Zone!\p"
	.string "Sorry, I didn't catch that!\p"
	.string "I can't hear you over all these\n"
	.string "wild Tauros...\p"
	.string "They kind of look like they're going\n"
	.string "to stampede!\p"
	.string "... ... ...\p"
	.string "I gotta go!$"

MatchCall_Text_ScottGotBadge6::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Even with his tricks, Koga didn't\n"
	.string "stand a chance!\p"
	.string "That's how many badges now?\p"
	.string "You're on quite a roll!$"

MatchCall_Text_ScottCinnabar::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Are you heading to Cinnabar Island\n"
	.string "to take on Blaine?\p"
	.string "I'll see you there!$"

MatchCall_Text_ScottGotBadge7::
	.string "Scott: Hey! Champ in the making!\p"
	.string "You could really feel the heat\n"
	.string "from that match!\p"
	.string "But don't get cocky!\n"
	.string "On to the next badge!$"

MatchCall_Text_ScottFinalBadge::
	.string "Scott: Hey! Champ in the making!\p"
	.string "So, one more badge to go!\p"
	.string "Did you hear that the Leader\n"
	.string "of Viridian City's Gym has\l"
	.string "returned?\p"
	.string "No one knows much about them,\n"
	.string "so this should prove interesting.$"

MatchCall_Text_ScottPkmnLeague::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Wow! All eight badges!\p"
	.string "Ever since I saw you face Brock,\n"
	.string "I knew you were different.\p"
	.string "But is that enough to beat the\n"
	.string "Elite Four?$"

MatchCall_Text_ScottThisIsIt::
	.string "Scott: Hey! Champ in the making!\p"
	.string "What can I say...\n"
	.string "You've made it to Indigo Plateau.\p"
	.string "Let's get this happening!$"

MatchCall_Text_ScottBattleTower::
	.string "{PLAYER}!\n"
	.string "You've done it.\p"
	.string "Come meet me at the Battle Tower.\n"
	.string "I have something for you…$"

MatchCall_Text_ScottBattleTower2::
	.string "{PLAYER}!\p"
	.string "Have you been enjoying the Battle\n"
	.string "Tower?\p"
	.string "Great! Keep aiming for the top!$"

MatchCall_Text_ScottGameClear::
	.string "Scott: Hey, champ in -!\p"
	.string "Wait, I guess it's just Champ\n"
	.string "now!\p"
	.string "But, I'll let you in on a little\n"
	.string "secret.\p"
	.string "Your journey doesn't end at the\n"
	.string "Pokémon League!\p"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "I'll call you when it's ready.$"

MatchCall_Text_Mom1::
	.string "Mom: Oh? {PLAYER}!\p"
	.string "I'm so happy you called!\p"
	.string "That means your Cell Phone\n"
	.string "must be working properly!\p"
	.string "You'll make lots of friends on\n"
	.string "your journey, so make sure to\l"
	.string "register them too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I'm your mom!\p"
	.string "I know everything about you!\p"
	.string "Hehehehe.\n"
	.string "See you soon, honey!$"

MatchCall_Text_Mom2::
	.string "Mom: I heard a very smart man lives\n"
	.string "near Cerulean City.\p"
	.string "I wonder how much money a Pokémaniac\n"
	.string "makes...\p"
	.string "Do you think it's more than a trainer?\p"
	.string "Maybe you should get some career advice\n"
	.string "from him.$"

MatchCall_Text_Mom3::
	.string "Mom: Your father and you…\n"
	.string "Everyone is captivated by Pokémon.\p"
	.string "What is the charm of Pokémon?\p"
	.string "Me?\n"
	.string "I adore Pokémon that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom4::
	.string "Mom: Lavendar Town…\n"
	.string "What a sad place…\p"
	.string "When I think about all those Pokémon…\p"
	.string "…\p"
	.string "I'm sorry, {PLAYER}.'\p"
	.string "I don't want to make you sad, too.$"

MatchCall_Text_Mom5::
	.string "Mom: {PLAYER}!\n"
	.string "I was just thinking about you.\p"
	.string "I wish there was a way I could help\n"
	.string "you more on your adventure.\p"
	.string "Maybe I could save your money for you!\p"
	.string "Oh? You're afraid I'd spend it all\n"
	.string "at the Celadon Department Store?\p"
	.string "How rude!$"

MatchCall_Text_Mom6::
	.string "Mom: Oh, you visited Fuchsia City?\p"
	.string "I used to love to visit the Safari\n"
	.string "Zone when I was your age!\p"
	.string "I loved the Safari Game,\n"
	.string "but I could never win.\p"
	.string "I always got lost!$"

MatchCall_Text_Mom7::
	.string "Mom: Oh, {PLAYER}!\p"
	.string "I was just watching the news.\n"
	.string "Team Rocket attacked Saffron!\p"
	.string "What is the world coming to.\n"
	.string "Please stay safe!$"

MatchCall_Text_Mom8::
	.string "Mom: You visited Cinnabar Island?\p"
	.string "When I was younger, my friends and\n"
	.string "I would swim out there!\p"
	.string "We were too scared to go into the\n"
	.string "Pokémon Mansion, though.\p"
	.string "The place gave me the creeps!$"

MatchCall_Text_Mom9::
	.string "Mom: Hi, {PLAYER}!\p"
	.string "You've been out there so long.\n"
	.string "I hope you're having fun!\p"
	.string "But you can always come home\n"
	.string "if things are getting too hard!$"

MatchCall_Text_MomGameClear::
	.string "Mom: {PLAYER}…\n"
	.string "It feels like you just left\n"
	.string "Pallet Town the other day, and\l"
	.string "now you've been all over Kanto!\p"
	.string "Who knew you'd have such an\n"
	.string "adventure with your Pokémon!\p"
	.string "I'm so proud of you!$"

MatchCall_Text_RegisteredRival:
	.string "Daisy registered {RIVAL}'s info\n"
	.string "in your Cell Phone.$"

MatchCall_Text_Rival1::
	.string "{RIVAL}: What? Who's calling me?\p"
	.string "...\p"
	.string "{PLAYER}? Who gave you my number?\p"
	.string "Ugh, my sister can be such a pain.\p"
	.string "Don't call me again!$"

MatchCall_Text_Rival2::
	.string "{RIVAL}: Oh, it's {PLAYER}?\p"
	.string "I couldn't hear you over the sound\n"
	.string "of all these badges I'm earning.\p"
	.string "What? You got one, too?\p"
	.string "That's a surprise!$"

MatchCall_Text_Rival3::
	.string "{RIVAL}: Calling me again?\p"
	.string "Don't think I'm going to give you\n"
	.string "any tips, {PLAYER}.\p"
	.string "I was born with this skill, it\p"
	.string "can't be taught!$"

MatchCall_Text_Rival4::
	.string "{RIVAL}: Oh, {PLAYER}.\p"
	.string "I heard a rumor you fell off\p"
	.string "the S.S. Anne.\p"
	.string "Guess that was too good to be true.$"

MatchCall_Text_Rival5::
	.string "{RIVAL}: Hey, {PLAYER}.\p"
	.string "You made it to Celadon?\p"
	.string "There's a great restaurant there,\n"
	.string "but they don't let losers like you\l"
	.string "eat there! Ha!$"

MatchCall_Text_Rival6::
	.string "{RIVAL}: Eww, {PLAYER}.\p"
	.string "Why do you keep calling me?\p"
	.string "You're like, obssessed or something.\p"
	.string "Don't be a weirdo!$"

MatchCall_Text_Rival7::
	.string "{RIVAL}: Can't talk, {PLAYER}.\p"
	.string "I'm facing down some Cool Trainers.'\p"
	.string "Yeah, it's two on one.\p"
	.string "I win those all the time.$"

MatchCall_Text_Rival8::
	.string "{RIVAL}: Hey, {PLAYER}.\p"
	.string "This is getting pretty real, huh?\p"
	.string "Remember when we used to play togeter\n"
	.string "as kids?.\p"
	.string "Who would have known I'd grown up to be\l"
	.string "the future champion of Kanto!$"

MatchCall_Text_Rival9::
	.string "{RIVAL}: {PLAYER}.\p"
	.string "I'm going to do it.\p"
	.string "I'm going to be the champion.\p"
	.string "Nobody can stop me.$"

MatchCall_Text_RivalGameClear::
	.string "{RIVAL}: Oh, it's you, {PLAYER}.\p"
	.string "Calling to rub it in my face?\p"
	.string "Listen, what happened at the League\n"
	.string "was a total fluke!\p"
	.string "I'll beat you next time!$"

MatchCall_Text_AideIntro::
	.string "Cedar: ……………\n"
	.string "Hello? Ah, {PLAYER}!\p"
	.string "This is Cedar! I'm one of the\n"
	.string "professor's aides!\p"
	.string "We met in Pallet Town, do you\n"
	.string "remember?\p"
	.string "Yes, yes! Good!\p"
	.string "The professor gave me your\n"
	.string "number. I hope that's alright.\p"
	.string "He's asked me to assist you on\n"
	.string "your journey, so I'll be checking\l"
	.string "on you again soon. Goodbye!$"

MatchCall_Text_AideIntro2::
	.string "Cedar: ……………\n"
	.string "Hello? Ah, {PLAYER}!\p"
	.string "This is Cedar! I'm one of the\n"
	.string "professor's aides!\p"
	.string "I've seen you at Oak's Lab, but\n"
	.string "we never had a chance to speak.\p"
	.string "The professor gave me your\n"
	.string "number. I hope that's alright.\p"
	.string "He's asked me to assist you on\n"
	.string "your journey, so I'll be checking\l"
	.string "on you again soon. Goodbye!$"

MatchCall_Text_RegisteredOaksAide:
	.string "Oak's Aide registered their info\n"
	.string "in your Cell Phone.$"

MatchCall_Text_AideWatchingProgress::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "How is your journey coming along?\p"
	.string "That's good!\p"
	.string "I'll be watching your progress!$"

MatchCall_EventScript_AideFlashReady::
	lockall
	pokenavcall MatchCall_Text_AideFlashReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE2
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideFlashReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 2, \n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute2::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 2\n"
	.string "as we speak!\p"
	.string "I think I took a wrong turn\n"
	.string "somewhere, though.\p"
	.string "I ended up in the East Building.\p"
	.string "It may be a little harder for you\n"
	.string "to get to me, so I'll be waiting!$"

MatchCall_EventScript_AideEverstoneReady::
	lockall
	pokenavcall MatchCall_Text_AideEverstoneReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE10
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideEverstoneReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 10, \n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute10::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 10\n"
	.string "as we speak!\p"
	.string "I ended up battling a few Trainers,\n"
	.string "so my Pokémon needs a rest.\p"
	.string "Meet me at the Pokémon Center!$"

MatchCall_EventScript_AideItemfinderReady::
	lockall
	pokenavcall MatchCall_Text_AideItemfinderReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE11
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideItemfinderReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 11,\n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute11::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 11\n"
	.string "as we speak!\p"
	.string "I wanted to get a good look at\n"
	.string "the ocean, so I'll try to find\l"
	.string "a spot to get a good look.$"

MatchCall_EventScript_AideAmuletCoinReady::
	lockall
	pokenavcall MatchCall_Text_AideAmuletCoinReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE16
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideAmuletCoinReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 16,\n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute16::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 16\n"
	.string "as we speak!\p"
	.string "There were some scary guys on\n"
	.string "the Cycling Road, so I'm going\l"
	.string "to stay in the Gate House!$"

MatchCall_EventScript_AideExpShareReady::
	lockall
	pokenavcall MatchCall_Text_AideExpShareReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE15
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideExpShareReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 15,\n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute15::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 15\n"
	.string "as we speak!\p"
	.string "Have you visited the Safari Zone?\p"
	.string "I tried to catch a super rare\n"
	.string "Pokémon, but it ran away!$"

MatchCall_Text_AideGameClear::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on becoming\n"
	.string "the champion!\p"
	.string "I hope my rewards were helpful!$"

MatchCall_Text_RegisteredLooker:
	.string "Looker registered their info in\n"
	.string "your Cell Phone.$"

MatchCall_Text_LookerIntro::
	.string "Looker: Team Rocket…\p"
	.string "They don't care who they\n"
	.string "hurt, as long as it makes\l"
	.string "them more money!\p"
	.string "People…\n"
	.string "Pokémon…\l"
	.string "We need to protect them!\p"
	.string "That's why I vowed to stop\n"
	.string "Team Rocket.$"

MatchCall_Text_LookerCeladon::
	.string "Looker: Hello, {PLAYER}!\p"
	.string "With their recruiting\n"
	.string "operation in Cerulean City\l"
	.string "shut down, we need to find\l"
	.string "out where Team Rocket is\l"
	.string "hiding out.\p"
	.string "My gut says its a nearby city,\n"
	.string "but it could be anywhere.\p"
	.string "Keep an eye out for anything\n"
	.string "suspicious!$"

MatchCall_Text_LookerRocketHideout::
	.string "Looker: Oh, its you, {PLAYER}.\n"
	.string "Thanks for the tip about Team\l"
	.string "Rocket's hideout in Celadon.\p"
	.string "That should certainly slow down\n"
	.string "their operation for some time!$"

MatchCall_Text_LookerSaffron::
	.string "Looker: I'm sorry {PLAYER}, but\n"
	.string "I don't have time to talk now!\p"
	.string "We intercepted some of Team\n"
	.string "Rocket's plans, and it looks like\l"
	.string "they're going to make their next\l"
	.string "move in Saffron City!\p"
	.string "...what!?\p"
	.string "You're saying they're already there?\n"
	.string "We're too late, again!\p"
	.string "Be careful, {PLAYER}!$"

MatchCall_Text_LookerSilphCo::
	.string "Looker: {PLAYER}, thanks again.\p"
	.string "We didn't get their leader, but\l"
	.string "we at least saved Saffron City.\p"
	.string "We'll find whoever is giving the\n"
	.string "orders, soon.\p"
	.string "Team Rocket's days are numbered!$"

MatchCall_Text_LookerGiovanni::
	.string "Looker: Giovanni may have gotten\n"
	.string "away, but this should be the end\l"
	.string "of Team Rocket.\p"
	.string "My team is in your debt!$"

MatchCall_EventScript_LookerPostgameReady::
	lockall
	pokenavcall MatchCall_Text_LookerPostgameReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_QUEUE_LOOKER_POSTGAME_CALL
	setflag FLAG_LOOKER_POSTGAME_STARTED
	clearflag FLAG_HIDE_SILPH_POSTGAME_ROCKET
	releaseall
	end

MatchCall_Text_LookerPostgameReady::
	.string "Looker: {PLAYER}!\p"
	.string "It's an emergency!\p"
	.string "Team Rocket has resurfaced in\n"
	.string "Saffron City!\p"
	.string "They've taken the Silph Co.\n"
	.string "President hostage again...\p"
	.string "...and theres something else...\p"
	.string "I'll tell you when you get here.\p"
	.string "You better come see me in\n"
	.string "Saffron right away.$"

MatchCall_Text_LookerPostgameWaiting::
	.string "Looker: {PLAYER}!\p"
	.string "Hurry to Saffron City!$"

MatchCall_Text_LookerPostgameCompleted::
	.string "Looker: Team Rocket!\p"
	.string "They'll try anything to get\n"
	.string "what they want.\p"
	.string "That's why we have to always\n"
	.string "stay vigilant!\p"
	.string "I'm glad Kanto has trainers\n"
	.string "like you helping out, {PLAYER}.$"

MatchCall_Text_RegisteredBill:
	.string "Bill registered their info in\n"
	.string "your Cell Phone.$"

MatchCall_Text_Bill1::
	.string "Bill: Thanks again for\n"
	.string "helping me out back there!\p"
	.string "Becoming a Pokémon...\p"
	.string "Man, what a trip!\p"
	.string "But it's giving me some new\n"
	.string "ideas for my inventions!\p"
	.string "Gotta go!$"

MatchCall_Text_Bill2::
	.string "Bill: Oh hey, {PLAYER}!\p"
	.string "Did you ever end up using\n"
	.string "the S.S. Ticket?\p"
	.string "Oh yeah? How was it?\p"
	.string "Ha! Well, why you were busy\n"
	.string "getting your sea legs, I had\l"
	.string "a few more ideas!\p"
	.string "Swing by the lab the next time\n"
	.string "you're in Cerulean and I'll show\l"
	.string "them to you!$"

MatchCall_Text_Bill3::
	.string "Bill: Hey, {PLAYER}!\p"
	.string "How's my DexNav app working?\p"
	.string "I'm sure it's helping you fill\n"
	.string "up your PokéDex pretty quick!$"

MatchCall_Text_Bill4::
	.string "Bill: Yo, {PLAYER}!\p"
	.string "Whoa! Team Rocket's leader was\n"
	.string "the Viridian Gym's leader, too?\p"
	.string "The net was buzzing with theories,\n"
	.string "but I don't think I saw anyone guess\l"
	.string "that one!\p"
	.string "Who knew he was hiding in plain sight!\p"
	.string "...\p"
	.string "That gives me an idea!\p"
	.string "Why don't you come back to the Sea\n"
	.string "Cottage.\p"
	.string "I'll be done by the time you get here!$"

MatchCall_Text_Bill5::
	.string "Bill: Hey, {PLAYER}!\p"
	.string "How's my DexNav app working?\p"
	.string "With the Detector Mode, it's going\n"
	.string "to be a breeze finding rare Pokémon!$"

MatchCall_Text_Bill6::
	.string "Bill: Wow, {PLAYER}!\p"
	.string "The footage from your battles are\n"
	.string "all over the net!\p"
	.string "People just can't get enough of you!\p"
	.string "I hope my inventions were helpful\n"
	.string "on your journey.\p"
	.string "Oh, me?\p"
	.string "I'll stick to the lab for now.\n"
	.string "Maybe I'll think of something new!\p"
	.string "Come visit sometime!$"

@Match Call Trainers
MatchCall_WildBattleText1::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just took a shot at catching\n"
	.string "this {STR_VAR_2}, but it took off.\p"
	.string "I came oh so close, too!\p"
	.string "It spoiled my day…\n"
	.string "All right, see you!$"

MatchCall_NegativeBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I tried battling another Trainer,\n"
	.string "but I lost.\p"
	.string "It was really disappointing.\n"
	.string "Well, see you again!$"	

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I battled another Trainer earlier.\n"
	.string "I won! I won!\p"
	.string "My {STR_VAR_2} really worked hard\n"
	.string "for me. This is so great!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Oh? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to battle now?\n"
	.string "I'll wait for you! See you!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Want to have a battle with me?\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"


@MC Group 2
MatchCall_WildBattleText2::
	.string "…Uh, {PLAYER}{KUN}?\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, wait! Wait!\n"
	.string "I can catch this {STR_VAR_2}…\p"
	.string "Aaarrrgh! It bolted loose!\n"
	.string "That wasn't just close!$"

MatchCall_NegativeBattleText2::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just got cleaned in a battle.\p"
	.string "I guess I need to raise my team\n"
	.string "some more!$"

MatchCall_PositiveBattleText2::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I was in a battle recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it,\n"
	.string "{PLAYER}{KUN}. Bye-bye!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts are you now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to battle now?\n"
	.string "I'll wait for you. See you!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How are your Pokémon doing?\p"
	.string "My Pokémon keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now,\n"
	.string "so let's battle if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

@MC Group 3
MatchCall_WildBattleText3::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "Have you had success catching\n"
	.string "Pokémon lately?\p"
	.string "I came very close a little while\n"
	.string "ago, but my target got free.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_NegativeBattleText3::
	.string "Hiya, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\p"
	.string "I've been battling on,\n"
	.string "but I haven't won very often.\p"
	.string "I can't get it together.\n"
	.string "Right, take care!$"

MatchCall_PositiveBattleText3::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I just won another one today!\p"
	.string "I'm on a roll! Gahahaha!\n"
	.string "Well, see you!$"

MatchCall_SameRouteBattleRequestText3::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let's battle.\n"
	.string "Right away, I mean.\p"
	.string "I'll show you my Pokémon.\n"
	.string "I'll wait for you.$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Are your Pokémon keeping well?\p"
	.string "My Pokémon have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "battle with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

@MC Group 4
MatchCall_WildBattleText4::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still catching Pokémon?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but it's not so easy.\p"
	.string "The way of Pokémon is deep!$"

MatchCall_NegativeBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been battling hard lately,\n"
	.string "but to little success.\p"
	.string "I can't get into the groove.\n"
	.string "You take care.$"

MatchCall_PositiveBattleText4::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "How's your battling?\p"
	.string "Me, I had a battle the other day,\n"
	.string "and my {STR_VAR_2} came up huge!\p"
	.string "The next time I battle you,\n"
	.string "{PLAYER}, it won't be me losing!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your Pokémon keeping?\p"
	.string "Oh, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "My Pokémon have grown a lot\n"
	.string "tougher since last time.\p"
	.string "I want to see how strong they've\n"
	.string "become with your Pokémon, {PLAYER}.\p"
	.string "So, let's have a battle!\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}.$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

@MC Group 5
MatchCall_WildBattleText5::
	.string "Hey, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've been thinking about trying\n"
	.string "to catch me some Pokémon.\p"
	.string "But I can't seem to find any.\n"
	.string "It's a real puzzler for me!\p"
	.string "I'm at my wit's end!\n"
	.string "See you around!$"

MatchCall_NegativeBattleText5::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going lately?\p"
	.string "I lost a battle yesterday,\n"
	.string "and it's filled my thoughts.\p"
	.string "I have to devise a plan…\n"
	.string "See you.$"

MatchCall_PositiveBattleText5::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been riding a hot streak.\n"
	.string "Why, I just won a battle.\p"
	.string "When we have our next battle,\n"
	.string "I'm sure not going to lose!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Are you keeping up?\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Oh, well, then don't you think we\n"
	.string "should battle?\p"
	.string "Don't keep me waiting too long!$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My Pokémon have grown pretty\n"
	.string "tough lately.\p"
	.string "Hey, how would you like to have\n"
	.string "another battle with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my Pokémon more.\n"
	.string "See you soon!$"
	
MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

@MC Personalized Text
MatchCall_PersonalizedText1::
	.string "Snivel… It's… {STR_VAR_1}…\n"
	.string "…Sob…\p"
	.string "My teacher chewed me out in class\n"
	.string "today.\p"
	.string "But I don't dislike her or anything.\p"
	.string "She tells me exactly what\n"
	.string "I did wrong so I can learn from it.\p"
	.string "You bet I'll be going to\n"
	.string "the Trainer's School tomorrow!\p"
	.string "See you later!$"

MatchCall_PersonalizedText2::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five Trainers again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_PersonalizedText3::
	.string "I'm {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I couldn't help\n"
	.string "but lose to you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "But win or lose, I like to battle\n"
	.string "when I'm camping.\p"
	.string "Battle with us again, okay?\n"
	.string "Oh, and let's go camping, too!$"

MatchCall_PersonalizedText4::
	.string "It's me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the mountains more?\p"
	.string "I rarely see you in the mountains…\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText5::
	.string "It's me, {STR_VAR_1}.\p"
	.string "I'm popular because I have lots\n"
	.string "of Bug Pokémon, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes Bug Pokémon so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText6::
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of Trainers every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText7::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It's {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That's all today…$"

MatchCall_PersonalizedText8::
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I'm fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText9::
	.string "It's me, {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "I think I could write a song about\n"
	.string "one of your adventures.\p"
	.string "…Oh, hey, I'm feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText10::
	.string "I love Pokémon!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "You have to hear this!\n"
	.string "My sweet Pokémon…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText11::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I'm seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "Maybe I'll try catching the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I'm kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText12::
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong Trainer\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText13::
	.string "Vrrrroooooooooooom!\p"
	.string "Hey! It's {STR_VAR_1}! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While riding my bike…\l"
	.string "Its dangerous!\p"
	.string "We'll chat…another time…\l"
	.string "I don't want to crash!!$"

MatchCall_PersonalizedText14::
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my Pokémon with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have Trainer\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText15::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I'm not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText16::
	.string "Ohoho!\p"
	.string "This is {STR_VAR_1}! I can't wait to\n"
	.string "tell you about my darling Pokémon!\p"
	.string "Please, you must listen to this.\n"
	.string "It's about my darling {STR_VAR_2}.\p"
	.string "Whenever anyone picks it up,\n"
	.string "it leaps straight into my arms!\p"
	.string "Oh… Oh… Could there be anything\n"
	.string "more blissful?\p"
	.string "Oh, it feels so heavenly!\p"
	.string "I'm so glad I could share some of\n"
	.string "my happiness with you.\p"
	.string "Well, I must be going.\n"
	.string "Bye, now!$"

MatchCall_PersonalizedText17::
	.string "Oh, it's {STR_VAR_1}, hello.\p"
	.string "I've been swimming a lot but I still\n"
	.string "can't seem to reach Cinnabar.\p"
	.string "Maybe I'm just going in circles.\p"
	.string "No, no, that can't be possible.\n"
	.string "Wahahaha.\l"
	.string "Take care!$"

MatchCall_PersonalizedText18::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How are your Pokémon doing?\p"
	.string "My Dragon Pokémon appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText19::
	.string "It is {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of juggling.\p"
	.string "But I have not been too successful.\p"
	.string "Sometimes I feel like my life is\l"
	.string "is just like my juggling balls...p"
	.string "Dropped on the ground, bouncing\n"
	.string "everywhere in chaos.\p"
	.string "Farewell!$"

MatchCall_PersonalizedText20::
	.string "Hello, this is {STR_VAR_1}…\p"
	.string "I've grown a little jaded with this\n"
	.string "whole Cooltrainer thing…\p"
	.string "Everyone thinks I'm a perfect\n"
	.string "Trainer, and that makes me try to\l"
	.string "live up to that expectation.\p"
	.string "But I guess that goes with being\n"
	.string "a Cooltrainer.\p"
	.string "I'll just have to buckle down…\n"
	.string "and grin and bear it.\p"
	.string "You're the only person that I could\n"
	.string "confide in like this.\p"
	.string "But when I see you next,\n"
	.string "don't worry, I won't whine!$"
