@UPDATED
MatchCall_Text_OakRegisterCall:
	.string "Oak: Oh, {PLAYER}{KUN}!\n"
	.string "I see you have a Cell Phone!\p"
	.string "Well, I should give you my number.\p"
	.string "That way, I'd be able to examine\n"
	.string "your Pokédex even while you're\l"
	.string "out in the field.$"

MatchCall_Text_RegisteredOak: 
	.string "Registered Professor Oak\n"
	.string "in your Cell Phone.$"

MatchCall_Text_RegisteredScott:
	.string "Registered Scott\n"
	.string "in your Cell Phone.$"

MatchCall_Text_ScottBusy::
	.string "… beep … beep … beep …\p"
	.string "Scott's line seems to be'\n"
	.string "busy…$"

MatchCall_Text_ScottCerulean::
	.string "Scott: Hey! Champ in the making!\p"
	.string "You made it to Cerulean City!\p"
	.string "You going to challenge Misty?\n"
	.string "Better bring a swimsuit! Ha!\p"
	.string "Let's see if I was right about\n"
	.string "you. See you at the gym!$"

MatchCall_Text_ScottGotBadge2::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Congratulations on earning your\n"
	.string "Cascade Badge!\p"
	.string "You're really getting the hang of this!$"

MatchCall_Text_ScottVermilion::
	.string "Scott: Hey! Champ in the making!\p"
	.string "I heard you reached Vermilion City!\p"
	.string "Planning to take on Lt. Surge?\p"
	.string "Great! I'll be watching!$"

MatchCall_Text_ScottGotBadge3::
	.string "Scott: Hey! Champ in the making!\p"
	.string "What a match! I knew you'd be able\n"
	.string "to get that Thunder Badge!\p"
	.string "But it only gets harder from here!$"

MatchCall_Text_ScottCeladon::
	.string "Scott: Hey! Champ in the making!\p"
	.string "So you made it to Celadon City!\p"
	.string "Maybe I'll take a break from the\n"
	.string "game corner and catch your match!$"

MatchCall_Text_ScottGotBadge4::
	.string "Scott: Hey! Champ in the making!\p"
	.string "I'm glad I didn't miss that match.\n"
	.string "What a show!\p"
	.string "You're definitely making a name for\n"
	.string "for yourself!$"

MatchCall_Text_ScottSaffron::
	.string "Scott: Hey! Champ in the making!\p"
	.string "I was hoping to catch you in\n"
	.string "Saffron City, but there were all\l"
	.string "these Team Rocket grunts around!\p"
	.string "Did you know anything about that?$"

MatchCall_Text_ScottGotBadge5::
	.string "Scott: Hey! Champ in the making!\p"
	.string "If Sabrina had read my mind,\n"
	.string "she'd know I never had any doubts!\p"
	.string "Great job earning your Marsh Badge!$"

MatchCall_Text_ScottFuchsia::
	.string "Scott: Hey! Champ in the making!\p"
	.string "What's that? You're in Fuchsia?\n"
	.string "City, too?\p"
	.string "Come again?\n"
	.string "Yeah! I'm over at the Safari Zone!\p"
	.string "Sorry, I didn't catch that!\p"
	.string "I can't hear you over all these\n"
	.string "wild Tauros...\p"
	.string "They kind of look like they're going\n"
	.string "to stampede!\p"
	.string "... ... ...\p"
	.string "I gotta go!$"

MatchCall_Text_ScottGotBadge6::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Even with his tricks, Koga didn't\n"
	.string "stand a chance!\p"
	.string "That's how many badges now?\p"
	.string "You're on quite a roll!$"

MatchCall_Text_ScottCinnabar::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Are you heading to Cinnabar Island\n"
	.string "to take on Blaine?\p"
	.string "I'll see you there!$"

MatchCall_Text_ScottGotBadge7::
	.string "Scott: Hey! Champ in the making!\p"
	.string "You could really feel the heat\n"
	.string "from that match!\p"
	.string "But don't get cocky!\n"
	.string "On to the next badge!$"

MatchCall_Text_ScottFinalBadge::
	.string "Scott: Hey! Champ in the making!\p"
	.string "So, one more badge to go!\p"
	.string "Did you hear that the Leader\n"
	.string "of Viridian City's Gym has\l"
	.string "returned?\p"
	.string "No one knows much about them,\n"
	.string "so this should prove interesting.$"

MatchCall_Text_ScottPkmnLeague::
	.string "Scott: Hey! Champ in the making!\p"
	.string "Wow! All eight badges!\p"
	.string "Ever since I saw you face Brock,\n"
	.string "I knew you were different.\p"
	.string "But is that enough to beat the\n"
	.string "Elite Four?$"

MatchCall_Text_ScottThisIsIt::
	.string "Scott: Hey! Champ in the making!\p"
	.string "What can I say...\n"
	.string "You've made it to Indigo Plateau.\p"
	.string "Let's get this happening!$"

MatchCall_Text_ScottNoService::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Scott appears to be out of\n"
	.string "the Cell Phone's service area…$"

MatchCall_Text_ScottGameClear::
	.string "Scott: Hey, champ in -!\p"
	.string "Wait, I guess it's just Champ\n"
	.string "now!\p"
	.string "But, I'll let you in on a little\n"
	.string "secret.\p"
	.string "Your journey doesn't end at the\n"
	.string "Pokémon League!\p"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "I'll call you when it's ready.$"

MatchCall_Text_Mom1::
	.string "Mom: Oh? {PLAYER}!\p"
	.string "I'm so happy you called!\p"
	.string "That means your Cell Phone\n"
	.string "must be working properly!\p"
	.string "You'll make lots of friends on\n"
	.string "your journey, so make sure to\l"
	.string "register them too!\p"
	.string "Good! Good!\n"
	.string "You seem to be quite happy!\p"
	.string "Hm…\n"
	.string "How could I know that?\p"
	.string "It's because I'm your mom!\p"
	.string "I know everything about you!\p"
	.string "Hehehehe.\n"
	.string "See you soon, honey!$"

MatchCall_Text_MomGameClear::
	.string "Mom: {PLAYER}…\n"
	.string "It feels like you just left\n"
	.string "Pallet Town the other day, and\l"
	.string "now you've been all over Kanto!\p"
	.string "Who knew you'd have such an\n"
	.string "adventure with your Pokémon!\p"
	.string "I'm so proud of you!$"

MatchCall_Text_RegisteredRival:
	.string "Registered {RIVAL}\n"
	.string "in your Cell Phone.$"

MatchCall_Text_Rival1::
	.string "{RIVAL}: What? Who's calling me?\p"
	.string "...\p"
	.string "{PLAYER}? Who gave you my number?\p"
	.string "Ugh, my sister can be such a pain.\p"
	.string "Don't call me again!$"

MatchCall_Text_RivalGameClear::
	.string "{RIVAL}: Oh, it's you, {PLAYER}.\p"
	.string "Calling to rub it in my face?\p"
	.string "Listen, what happened at the League\n"
	.string "was a total fluke!\p"
	.string "I'll beat you next time!$"

MatchCall_Text_AideIntro::
	.string "Cedar: ……………\n"
	.string "Hello? Ah, {PLAYER}!\p"
	.string "This is Cedar! I'm one of the\n"
	.string "professor's aides!\p"
	.string "We met in Pallet Town, do you\n"
	.string "remember?\p"
	.string "Yes, yes! Good!\p"
	.string "The professor gave me your\n"
	.string "number. I hope that's alright.\p"
	.string "He's asked me to assist you on\n"
	.string "your journey, so I'll be checking\l"
	.string "on you again soon. Goodbye!$"

MatchCall_Text_AideIntro2::
	.string "Cedar: ……………\n"
	.string "Hello? Ah, {PLAYER}!\p"
	.string "This is Cedar! I'm one of the\n"
	.string "professor's aides!\p"
	.string "I've seen you at Oak's Lab, but\n"
	.string "we never had a chance to speak.\p"
	.string "The professor gave me your\n"
	.string "number. I hope that's alright.\p"
	.string "He's asked me to assist you on\n"
	.string "your journey, so I'll be checking\l"
	.string "on you again soon. Goodbye!$"

MatchCall_Text_RegisteredOaksAide:
	.string "Registered Oak's Aide\n"
	.string "in your Cell Phone.$"

MatchCall_Text_AideWatchingProgress::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "How is your journey coming along?\p"
	.string "That's good!\p"
	.string "I'll be watching your progress!$"

MatchCall_EventScript_AideFlashReady::
	lockall
	pokenavcall MatchCall_Text_AideFlashReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE2
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideFlashReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 2, \n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute2::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 2\n"
	.string "as we speak!\p"
	.string "I think I took a wrong turn\n"
	.string "somewhere, though.\p"
	.string "I ended up in the East Building.\p"
	.string "It may be a little harder for you\n"
	.string "to get to me, so I'll be waiting!$"

MatchCall_EventScript_AideEverstoneReady::
	lockall
	pokenavcall MatchCall_Text_AideEverstoneReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE10
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideEverstoneReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 10, \n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute10::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 10\n"
	.string "as we speak!\p"
	.string "I ended up battling a few Trainers,\n"
	.string "so my Pokémon needs a rest.\p"
	.string "Meet me at the Pokémon Center!$"

MatchCall_EventScript_AideItemfinderReady::
	lockall
	pokenavcall MatchCall_Text_AideItemfinderReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE11
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideItemfinderReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 11,\n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute11::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 11\n"
	.string "as we speak!\p"
	.string "I wanted to get a good look at\n"
	.string "the ocean, so I'll try to find\l"
	.string "a spot to get a good look.$"

MatchCall_EventScript_AideAmuletCoinReady::
	lockall
	pokenavcall MatchCall_Text_AideAmuletCoinReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE16
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideAmuletCoinReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 16,\n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute16::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 16\n"
	.string "as we speak!\p"
	.string "There were some scary guys on\n"
	.string "the Cycling Road, so I'm going\l"
	.string "to stay in the Gate House!$"

MatchCall_EventScript_AideExpShareReady::
	lockall
	pokenavcall MatchCall_Text_AideExpShareReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE15
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideExpShareReady::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on earning\n"
	.string "another Gym Badge!\p"
	.string "Professor Oak would like to\n"
	.string "give you a reward.\p"
	.string "If you meet me on Route 15,\n"
	.string "I will deliver it to you!$"

MatchCall_Text_AideOnMyWayRoute15::
	.string "Cedar: Hello, {PLAYER}!\p"
	.string "I'm headed towards Route 15\n"
	.string "as we speak!\p"
	.string "Have you visited the Safari Zone?\p"
	.string "I tried to catch a super rare\n"
	.string "Pokémon, but it ran away!$"

MatchCall_Text_AideGameClear::
	.string "Cedar: Ah, hello {PLAYER}!\p"
	.string "Congratulations on becoming\n"
	.string "the champion!\p"
	.string "I hope my rewards were helpful!$"

MatchCall_Text_RegisteredLooker:
	.string "Registered Looker\n"
	.string "in your Cell Phone.$"

MatchCall_Text_LookerIntro::
	.string "Looker: Team Rocket…\p"
	.string "They don't care who they\n"
	.string "hurt, as long as it makes\l"
	.string "them more money!\p"
	.string "People…\n"
	.string "Pokémon…\l"
	.string "We need to protect them!\p"
	.string "That's why I vowed to stop\n"
	.string "Team Rocket.$"

MatchCall_Text_LookerCeladon::
	.string "Looker: Hello, {PLAYER}!\p"
	.string "With their recruiting\n"
	.string "operation in Cerulean City\l"
	.string "shut down, we need to find\l"
	.string "out where Team Rocket is\l"
	.string "hiding out.\p"
	.string "My gut says its a nearby city,\n"
	.string "but it could be anywhere.\p"
	.string "Keep an eye out for anything\n"
	.string "suspicious!$"

MatchCall_Text_LookerRocketHideout::
	.string "Looker: Oh, its you, {PLAYER}.\n"
	.string "Thanks for the tip about Team\l"
	.string "Rocket's hideout in Celadon.\p"
	.string "That should certainly slow down\n"
	.string "their operation for some time!$"

MatchCall_Text_LookerSaffron::
	.string "Looker: I'm sorry {PLAYER}, but\n"
	.string "I don't have time to talk now!\p"
	.string "We intercepted some of Team\n"
	.string "Rocket's plans, and it looks like\l"
	.string "they're going to make their next\l"
	.string "move in Saffron City!\p"
	.string "...what!?\p"
	.string "You're saying they're already there?\n"
	.string "We're too late, again!\p"
	.string "Be careful, {PLAYER}!$"

MatchCall_Text_LookerSilphCo::
	.string "Looker: {PLAYER}, thanks again.\p"
	.string "We didn't get their leader, but\l"
	.string "we at least saved Saffron City.\p"
	.string "We'll find whoever is giving the\n"
	.string "orders, soon.\p"
	.string "Team Rocket's days are numbered!$"

MatchCall_Text_LookerGiovanni::
	.string "Looker: Giovanni may have gotten\n"
	.string "away, but this should be the end\l"
	.string "of Team Rocket.\p"
	.string "My team is in your debt!$"

MatchCall_Text_RegisteredBill:
	.string "Registered Bill\n"
	.string "in your Cell Phone.$"

MatchCall_Text_Bill1::
	.string "Bill: Thanks again for\n"
	.string "helping me out back there!\p"
	.string "Becoming a Pokémon...\p"
	.string "Man, what a trip!\p"
	.string "But it's giving me some new\n"
	.string "ideas for my inventions!\p"
	.string "Gotta go!$"

@UNUSED
MatchCall_Text_Mom2::
	.string "Mom: Your father and you…\n"
	.string "Everyone is captivated by Pokémon.\p"
	.string "What is the charm of Pokémon?\p"
	.string "Me?\n"
	.string "I adore Pokémon that help me with\l"
	.string "my everyday chores.$"

MatchCall_WildBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I saw this {STR_VAR_2} a while back\n"
	.string "but I couldn't catch it.\p"
	.string "It was so close, too!\n"
	.string "Well, see you again!$"

MatchCall_WildBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I tried to catch a nice {STR_VAR_2}\n"
	.string "a little while ago.\p"
	.string "But, it got away.\n"
	.string "I was sure disappointed!\p"
	.string "Okay, bye!$"

MatchCall_WildBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just took a shot at catching\n"
	.string "this {STR_VAR_2}, but it took off.\p"
	.string "I came oh so close, too!\p"
	.string "It spoiled my day…\n"
	.string "All right, see you!$"

MatchCall_WildBattleText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "You know the Pokémon {STR_VAR_2}?\n"
	.string "I came close to getting one.\p"
	.string "It was just a while back.\n"
	.string "I thought I had it but it escaped.\p"
	.string "If I see it again, I'll get it for\n"
	.string "sure, though.\p"
	.string "Okay, catch you later.$"

MatchCall_WildBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "Catching any Pokémon lately?\p"
	.string "A little while ago I came close to\n"
	.string "nabbing one, but it got loose.\p"
	.string "Right, take care!$"

MatchCall_WildBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "Caught any Pokémon lately?\p"
	.string "I nearly nabbed one the other day.\n"
	.string "But it evaded me somehow.\p"
	.string "You take care.$"

MatchCall_WildBattleText7::
	.string "…Uh, {PLAYER}{KUN}?\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, wait! Wait!\n"
	.string "I can catch this {STR_VAR_2}…\p"
	.string "Aaarrrgh! It bolted loose!\n"
	.string "That wasn't just close!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "Have you had success catching\n"
	.string "Pokémon lately?\p"
	.string "I came very close a little while\n"
	.string "ago, but my target got free.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "So? Are you getting more Pokémon\n"
	.string "together?\p"
	.string "I'm having a rotten time of it!\n"
	.string "They all get away from me!\p"
	.string "See you!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Listen, I came within a whisker of\n"
	.string "catching this {STR_VAR_2}…\p"
	.string "But, it gave me the slip…\p"
	.string "I need to try harder.\n"
	.string "See you around.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "I tried to catch a wild {STR_VAR_2}\n"
	.string "earlier, but it managed to flee.\p"
	.string "I feel defeated…$"

MatchCall_WildBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still catching Pokémon?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but it's not so easy.\p"
	.string "The way of Pokémon is deep!$"

MatchCall_WildBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Have you been catching Pokémon?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but with little success.\p"
	.string "The way of Pokémon is deep!$"

MatchCall_WildBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Just now, I tried to catch a cute\n"
	.string "{STR_VAR_2}.\p"
	.string "It got away, though!\n"
	.string "Oh, you bet I was disappointed!\p"
	.string "Bye-bye!$"

MatchCall_WildBattleText15::
	.string "Hey, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've been thinking about trying\n"
	.string "to catch me some Pokémon.\p"
	.string "But I can't seem to find any.\n"
	.string "It's a real puzzler for me!\p"
	.string "I'm at my wit's end!\n"
	.string "See you around!$"

MatchCall_NegativeBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I tried battling another Trainer,\n"
	.string "but I lost.\p"
	.string "It was really disappointing.\n"
	.string "Well, see you again!$"

MatchCall_NegativeBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I challenged someone else after\n"
	.string "we battled.\p"
	.string "I came close, but I ended up\n"
	.string "losing. Oh, well!$"

MatchCall_NegativeBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just got cleaned in a battle.\p"
	.string "I guess I need to raise my team\n"
	.string "some more!$"

MatchCall_NegativeBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I tried another battle yesterday,\n"
	.string "but I couldn't pull out the win.\p"
	.string "My team needs more raising.\n"
	.string "Okay, catch you later.$"

MatchCall_NegativeBattleText5::
	.string "Hiya, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\p"
	.string "I've been battling on,\n"
	.string "but I haven't won very often.\p"
	.string "I can't get it together.\n"
	.string "Right, take care!$"

MatchCall_NegativeBattleText6::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been battling hard lately,\n"
	.string "but to little success.\p"
	.string "I can't get into the groove.\n"
	.string "You take care.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going lately?\p"
	.string "I lost a battle yesterday,\n"
	.string "and it's filled my thoughts.\p"
	.string "I have to devise a plan…\n"
	.string "See you.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "How are your Pokémon doing?\n"
	.string "I lost a match the other day.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Listen, listen, you have to hear\n"
	.string "this!\p"
	.string "I had a Pokémon battle earlier,\n"
	.string "but I lost at the last second.\p"
	.string "Oh, it burns me up!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "A little earlier, I was in a battle.\n"
	.string "I lost, though.\p"
	.string "I need to raise my Pokémon more.\n"
	.string "See you around.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are your Pokémon?\p"
	.string "I just lost yet another battle.\p"
	.string "Well, see you!$"

MatchCall_NegativeBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still battling hard?\p"
	.string "As for me, I lost recently, so I've\n"
	.string "been training my team all over.\p"
	.string "Let's meet again.$"

MatchCall_NegativeBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\p"
	.string "I was in a battle just a little\n"
	.string "while before this.\p"
	.string "{PLAYER}{KUN}, try to be active like me.\n"
	.string "See you again!$"

MatchCall_NegativeBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Are you doing good?\p"
	.string "You should go home every so often,\n"
	.string "though.\p"
	.string "Bye-bye!$"

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I battled another Trainer earlier.\n"
	.string "I won! I won!\p"
	.string "My {STR_VAR_2} really worked hard\n"
	.string "for me. This is so great!$"

MatchCall_PositiveBattleText2::
	.string "Hello, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "I had a battle yesterday and\n"
	.string "I won! It's fantastic!$"

MatchCall_PositiveBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "How's your battling?\p"
	.string "Me, I had a battle the other day,\n"
	.string "and my {STR_VAR_2} came up huge!\p"
	.string "The next time I battle you,\n"
	.string "{PLAYER}, it won't be me losing!$"

MatchCall_PositiveBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I had a match earlier.\n"
	.string "I managed to win, but it was close.\p"
	.string "My {STR_VAR_2} put on one\n"
	.string "inspired showing.$"

MatchCall_PositiveBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Battling much?\p"
	.string "I just won a while back!\n"
	.string "My {STR_VAR_2} was brilliant!\p"
	.string "You wait. I'm going to beat you\n"
	.string "next time! Right, take care!$"

MatchCall_PositiveBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been riding a hot streak.\n"
	.string "Why, I just won a battle.\p"
	.string "When we have our next battle,\n"
	.string "I'm sure not going to lose!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} is a force!\n"
	.string "It won me another battle just now!\p"
	.string "I can't wait to have a rematch\n"
	.string "with you.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you've been well.\n"
	.string "I wanted to tell you I just won.\p"
	.string "My {STR_VAR_2} worked especially\n"
	.string "hard to get the win.\p"
	.string "See you again!$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "How are your Pokémon holding up?\n"
	.string "Mine just won a battle!\p"
	.string "My {STR_VAR_2} was spectacular,\n"
	.string "I must say!\p"
	.string "I wish I could've shown you!\n"
	.string "See you again!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How has life been treating you?\p"
	.string "My Pokémon appear to be charged\n"
	.string "with energy.\p"
	.string "I just won a battle with them.\n"
	.string "See you around.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I just won another one today!\p"
	.string "I'm on a roll! Gahahaha!\n"
	.string "Well, see you!$"

MatchCall_PositiveBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I trust you've been well?\n"
	.string "I'm still bursting with life!\p"
	.string "Why, just now, I won another match.\n"
	.string "I'm not stepping aside to you\l"
	.string "youngsters yet!$"

MatchCall_PositiveBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "I still have a bounce in my step!\p"
	.string "Why, I just won a battle yet again.\n"
	.string "Oh, I won't lose to young people\l"
	.string "quite yet!\p"
	.string "See you again!$"

MatchCall_PositiveBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I was in a battle recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it,\n"
	.string "{PLAYER}{KUN}. Bye-bye!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Huh? Wait, you're near\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, wow, we have to battle, then!\n"
	.string "I'll be waiting! See you!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Oh? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to battle now?\n"
	.string "I'll wait for you! See you!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, hey, are you near\n"
	.string "{STR_VAR_2} right now?\p"
	.string "How would you like to battle with\n"
	.string "me right now?\p"
	.string "I'm not losing again!\n"
	.string "I'll be waiting! Catch you soon!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts are you now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to battle now?\n"
	.string "I'll wait for you. See you!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "You're where now?\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, how about we have a quick\n"
	.string "rematch right away?\p"
	.string "I'll keep an eye out for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your Pokémon keeping?\p"
	.string "Oh, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let's battle.\n"
	.string "Right away, I mean.\p"
	.string "I'll show you my Pokémon.\n"
	.string "I'll wait for you.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "Would you like to have a battle\n"
	.string "with me, then?\p"
	.string "I'll wait for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Are you keeping up?\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Oh, well, then don't you think we\n"
	.string "should battle?\p"
	.string "Don't keep me waiting too long!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "We should have a battle now, then.\p"
	.string "I'm ready and waiting.\n"
	.string "Be quick!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Ah, so where you are now is\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we just have to have\n"
	.string "a battle, don't you think?\p"
	.string "I'll wait around for you!\n"
	.string "See you real quick!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "{STR_VAR_2}?\n"
	.string "That's quite close by!\p"
	.string "What do you say we have a battle\n"
	.string "now?\p"
	.string "I can wait.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Since that's not very far away,\n"
	.string "come see me for a battle.\p"
	.string "I'll wait for you.\n"
	.string "Bye for now.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You're what? …{STR_VAR_2}?\n"
	.string "That's very close.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle?\p"
	.string "I'll be looking for you!\n"
	.string "Bye-bye!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Want to have a battle with me?\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Would you like to have a battle\n"
	.string "with me again?\p"
	.string "You can find me around\n"
	.string "{STR_VAR_2}. I'll be waiting!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "My Pokémon have grown a lot\n"
	.string "tougher since last time.\p"
	.string "I want to see how strong they've\n"
	.string "become with your Pokémon, {PLAYER}.\p"
	.string "So, let's have a battle!\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My Pokémon have grown pretty\n"
	.string "tough lately.\p"
	.string "Hey, how would you like to have\n"
	.string "another battle with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "My Pokémon are growing up in\n"
	.string "decent ways.\p"
	.string "I'd really like to have another\n"
	.string "battle with you.\p"
	.string "I'll keep an eye out for you around\n"
	.string "{STR_VAR_2}. See you soon!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you're on top of things.\p"
	.string "I was thinking I'd like another\n"
	.string "battle with you. What do you say?\p"
	.string "If you feel like a battle,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Are your Pokémon growing?\p"
	.string "Mine sure got stronger.\n"
	.string "I'd like to show you.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me for a match.\p"
	.string "See you around.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "My Pokémon are very frisky.\p"
	.string "If you're ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Until then, good-bye!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How are your Pokémon doing?\p"
	.string "My Pokémon keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now,\n"
	.string "so let's battle if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My Pokémon have grown much\n"
	.string "stronger than before.\p"
	.string "I'd love another battle with you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me if you're close.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "My Pokémon are full of life.\n"
	.string "They appear to be looking forward\l"
	.string "to seeing your Pokémon, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now.\n"
	.string "I hope you'll seek us out.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I should tell you, my Pokémon have\n"
	.string "grown to be quite robust lately.\p"
	.string "I would like to see them in a battle\n"
	.string "with you, {PLAYER}{KUN}.\p"
	.string "We'll be around {STR_VAR_2}.\n"
	.string "Come see us anytime!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Are your Pokémon keeping well?\p"
	.string "My Pokémon have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "battle with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Oh, yes! My Pokémon are\n"
	.string "much stronger than before.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle, {PLAYER}{KUN}?\p"
	.string "We'll be waiting for you around\n"
	.string "{STR_VAR_2}.\p"
	.string "Come see us anytime, okay?$"

MatchCall_PersonalizedText1::
	.string "It's me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the mountains more?\p"
	.string "I rarely see you in the mountains…\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new Trainer\n"
	.string "about you.\p"
	.string "I told her about a strong Trainer\n"
	.string "who raises Pokémon with care.\p"
	.string "I hope you'll become a Trainer\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText3::
	.string "Hello! It's {STR_VAR_1}.\p"
	.string "I love where I am now.\n"
	.string "It's pleasant with sweet aromas!\p"
	.string "I think someone planted Berries,\n"
	.string "and they burst into bloom.\p"
	.string "See you again sometime!$"

MatchCall_PersonalizedText4::
	.string "Hello! Thirty years of exploration,\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems that you're energetically\n"
	.string "traveling here and there.\p"
	.string "Have you discovered any new ruins?\n"
	.string "Please tell if you have!\p"
	.string "Now, if you'll excuse me,\n"
	.string "I have ruins to explore.$"

MatchCall_PersonalizedText5::
	.string "It's {STR_VAR_1}!\p"
	.string "Know what I'm doing today?\n"
	.string "Looking at waves from the beach!\p"
	.string "Sigh… The waves are all sparkly.\n"
	.string "The sea is the prettiest from here.\l"
	.string "I'm getting hungry, so bye-bye!$"

MatchCall_PersonalizedText6::
	.string "Munch-chew…\n"
	.string "Oh, hi, it's {STR_VAR_1}.\l"
	.string "I love eating on the beach.\p"
	.string "My Pokémon and I have been doing\n"
	.string "great. We're fully fueled!\l"
	.string "I'm going for a swim. Bye!$"

MatchCall_PersonalizedText7::
	.string "Hello, this is {STR_VAR_1}…\p"
	.string "I've grown a little jaded with this\n"
	.string "whole Cooltrainer thing…\p"
	.string "Everyone thinks I'm a perfect\n"
	.string "Trainer, and that makes me try to\l"
	.string "live up to that expectation.\p"
	.string "But I guess that goes with being\n"
	.string "a Cooltrainer.\p"
	.string "I'll just have to buckle down…\n"
	.string "and grin and bear it.\p"
	.string "You're the only person that I could\n"
	.string "confide in like this.\p"
	.string "But when I see you next,\n"
	.string "don't worry, I won't whine!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my Pokémon with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have Trainer\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText9::
	.string "It's {STR_VAR_1}…\n"
	.string "Right now, behind you…\l"
	.string "Wasn't there something…?\p"
	.string "The power of the Pokémon that\n"
	.string "sleep here at Mt. Pyre…\p"
	.string "It's telling me about you…\p"
	.string "You should walk away quickly and\n"
	.string "never once look back…\p"
	.string "Giggle…\n"
	.string "Farewell…$"

MatchCall_PersonalizedText10::
	.string "This is {STR_VAR_1}.\n"
	.string "How do you do?\p"
	.string "Isn't it convenient that we can\n"
	.string "chat like this at a distance?\p"
	.string "Before, if I wanted to speak with\n"
	.string "anyone, I had to have my father\l"
	.string "drive me…\p"
	.string "I should be going now.\n"
	.string "I'm glad we had this chat.$"

MatchCall_PersonalizedText11::
	.string "It's {STR_VAR_1}!\n"
	.string "Will you listen to this?\p"
	.string "I like the Safari Zone a lot,\n"
	.string "but whenever I go, I get lost!\p"
	.string "All that tall grass!\n"
	.string "And it's much too spread out!\p"
	.string "I feel better getting that off\n"
	.string "my chest!\p"
	.string "I'm off to the Safari Zone again!\n"
	.string "Catch you!$"

MatchCall_PersonalizedText12::
	.string "Hello, {STR_VAR_1} here.\n"
	.string "Yes, correct, I am rich, yes.\p"
	.string "I should tell you, my wealth has\n"
	.string "grown since we last met.\p"
	.string "What's more, my Pokémon have also\n"
	.string "grown stronger.\p"
	.string "I can't shake the feeling that\n"
	.string "this world exists for me!\p"
	.string "Oh, no need to say a word!\n"
	.string "Everyone knows it's true!\p"
	.string "Oh, you must excuse me, I have this\n"
	.string "formal dinner to attend.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I'm seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "Maybe I'll try catching the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I'm kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText14::
	.string "Oh, it's {STR_VAR_1}!\p"
	.string "I was just thinking I'm getting\n"
	.string "bored of the Abandoned Ship.\p"
	.string "But since I'm already here,\n"
	.string "and I want to beat you once,\l"
	.string "I'll be sticking around a bit more.\p"
	.string "If you feel compelled, why don't\n"
	.string "you come see me?\p"
	.string "I think today will be the day that\n"
	.string "I finally challenge the man next\l"
	.string "door to a match.\p"
	.string "Be seeing you!$"

MatchCall_PersonalizedText15::
	.string "I'm {STR_VAR_1}!\n"
	.string "The man of the sea!\p"
	.string "You know what I think?\p"
	.string "The Trainers out at sea are\n"
	.string "the toughest of the tough!\p"
	.string "You should learn from me and train\n"
	.string "in the sea…\p"
	.string "Whoops, giant surf rising!\p"
	.string "It's a great training opportunity!\n"
	.string "Sorry, but I have to go!$"

MatchCall_PersonalizedText16::
	.string "It's {STR_VAR_1}! Listen, I've been\n"
	.string "teaching karate to my Pokémon.\p"
	.string "But now they're better than me!\n"
	.string "I've done nothing but lose to them!\p"
	.string "But even though I may lose to\n"
	.string "Pokémon, I won't lose to another\l"
	.string "Trainer, no sir!\p"
	.string "We have to battle again!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "It's me, {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "I think I could write a song about\n"
	.string "one of your episodes.\p"
	.string "…Oh, hey, I'm feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText18::
	.string "This is {STR_VAR_1}…\n"
	.string "Hear my new song.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Why are you that {STR_VAR_2}?\l"
	.string "Why can't I be you, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} and {STR_VAR_1},\l"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "Repeat chorus, fade…$"

MatchCall_PersonalizedText19::
	.string "I'm {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I couldn't help\n"
	.string "but lose to you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "But win or lose, I like to battle\n"
	.string "when I'm camping.\p"
	.string "Battle with us again, okay?\n"
	.string "Oh, and let's go camping, too!$"

MatchCall_PersonalizedText20::
	.string "It's me, me, {STR_VAR_1}!\p"
	.string "I'd like to climb other mountains\n"
	.string "than this one, to be honest.\p"
	.string "But I'm not sure if there'd be any\n"
	.string "ladies like on Mt. Chimney.\p"
	.string "If you know any other mountain\n"
	.string "with ladies around, let me know!\p"
	.string "Ehehehe, see you around!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It's {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That's all today…$"

MatchCall_PersonalizedText22::
	.string "This is {STR_VAR_1}. Today, I had\n"
	.string "this feeling I would chat with you.\p"
	.string "My desire to defeat you builds\n"
	.string "by day and by night.\p"
	.string "You have a rival like that, yes?\n"
	.string "I wish it were me…\p"
	.string "I'm glad you heard me out.\n"
	.string "See you!$"

MatchCall_PersonalizedText23::
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong Trainer\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText24::
	.string "Hello, this is {STR_VAR_1}.\n"
	.string "You sound well, {PLAYER}{KUN}.\p"
	.string "I've traveled around the world,\n"
	.string "but I must say I've taken a great\l"
	.string "shine to this region.\p"
	.string "I plan to stay here a while.\n"
	.string "Perhaps we can meet again?\p"
	.string "I've not forgotten your dazzling\n"
	.string "techniques.\p"
	.string "I do hope for a rematch.$"

MatchCall_PersonalizedText25::
	.string "Snivel… It's… {STR_VAR_1}…\n"
	.string "…Sob…\p"
	.string "Roxanne chewed me out in class\n"
	.string "today.\p"
	.string "But I don't dislike her or anything.\p"
	.string "Roxanne tells me exactly what\n"
	.string "I did wrong so I can learn from it.\p"
	.string "You bet I'll be going to\n"
	.string "the Trainer's School tomorrow!\p"
	.string "See you later!$"

MatchCall_PersonalizedText26::
	.string "It's {STR_VAR_1}!\p"
	.string "Roxanne let me battle with her\n"
	.string "yesterday.\p"
	.string "The results…\n"
	.string "Terrible, like you needed to ask.\p"
	.string "But I was delighted that Roxanne\n"
	.string "would even let me challenge her!\p"
	.string "You wouldn't believe how much\n"
	.string "more I admire her!\p"
	.string "I'm going to really focus and work!\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText27::
	.string "Hi, it's Anna! I'm with my junior\n"
	.string "partner Meg again today.\p"
	.string "I really love caring for Meg and\n"
	.string "Pokémon. They're so cute!\p"
	.string "I wish I could look after them\n"
	.string "as if they were my siblings!\p"
	.string "Oh, hi, Meg!\n"
	.string "Did you get the buns?\p"
	.string "Huh? No, no, I'm not treating you\n"
	.string "like my personal slave!\p"
	.string "You lost the match, so you have\n"
	.string "to go buy the bread as punishment!\p"
	.string "I wouldn't treat you like a slave,\n"
	.string "Meg! You're too special to me!\p"
	.string "I have to go now.\n"
	.string "It's time for our snack!$"

MatchCall_PersonalizedText28::
	.string "I love Pokémon!\n"
	.string "It's {STR_VAR_1} from the Fan Club!\p"
	.string "You have to hear this!\n"
	.string "My sweet Pokémon…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "This is {STR_VAR_1}! I can't wait to\n"
	.string "tell you about my darling Pokémon!\p"
	.string "Please, you must listen to this.\n"
	.string "It's about my darling {STR_VAR_2}.\p"
	.string "Whenever anyone picks it up,\n"
	.string "it leaps straight into my arms!\p"
	.string "Oh… Oh… Could there be anything\n"
	.string "more blissful?\p"
	.string "Oh, it feels so heavenly!\p"
	.string "I'm so glad I could share some of\n"
	.string "my happiness with you.\p"
	.string "Well, I must be going.\n"
	.string "Bye, now!$"

MatchCall_PersonalizedText30::
	.string "I am… {STR_VAR_1}.\n"
	.string "People call me an Expert.\p"
	.string "But there is one thing I know.\n"
	.string "I could not be an Expert on my own\l"
	.string "power.\p"
	.string "Only with the help of Pokémon can\n"
	.string "a Trainer become an Expert.\p"
	.string "Humph! I believe I may have said\n"
	.string "something deep and profound!\p"
	.string "I shall leave you in good spirits!$"

MatchCall_PersonalizedText31::
	.string "It's {STR_VAR_1}.\n"
	.string "I'm glad to chat with you!\p"
	.string "I am feeling alive and refreshed\n"
	.string "soaking in this hot-spring tub.\p"
	.string "I've been battling young Trainers\n"
	.string "since we met, but you're still\l"
	.string "the best of the lot.\p"
	.string "I imagine you'll become an Expert\n"
	.string "in your old age! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Yay! This is {STR_VAR_1}!\n"
	.string "What's up?\p"
	.string "I might be imagining this, but when\n"
	.string "I win battles, my shorts seem to\l"
	.string "feel, like, better. Materially.\p"
	.string "What do I mean by that?\n"
	.string "It's kind of hard to explain, but…\l"
	.string "How would I say this now…\l"
	.string "My shorts feel silkier!\p"
	.string "And when I battled you, {PLAYER}{KUN},\n"
	.string "my shorts felt icky and coarse.\p"
	.string "… … … … … …\n"
	.string "You didn't really believe that?\l"
	.string "Ehehehe, that's all! Bye now!$"

MatchCall_PersonalizedText33::
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I'm fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText34::
	.string "Hey, there! It's {STR_VAR_1}.\n"
	.string "Are you taking it casually?\p"
	.string "Ever since I was a kid, you know,\n"
	.string "I've always been placid, huh?\p"
	.string "I never was much for getting all\n"
	.string "stressed or rushing things.\p"
	.string "But wouldn't you know it,\n"
	.string "I'm now a Triathlete.\p"
	.string "You just can't tell where life will\n"
	.string "take you, if you get my drift.\p"
	.string "You're a Trainer now, but who\n"
	.string "knows what the future holds, huh?\p"
	.string "Imagine yourself as a teacher,\n"
	.string "or maybe an artist. Cool, huh?\p"
	.string "But, hey, be cool. Take it casual.\n"
	.string "See you around.$"

MatchCall_PersonalizedText35::
	.string "This is {STR_VAR_1}!\n"
	.string "I'm cycling right now.\p"
	.string "I love swimming and running,\n"
	.string "but cycling is my first love!\p"
	.string "It makes my whole body feel as if\n"
	.string "I'm one with the wind.\p"
	.string "It exhilarates me as if I were\n"
	.string "flying!\p"
	.string "Okay! Today, I'm going to set a new\n"
	.string "Cycling Road record!\p"
	.string "You should make the challenge, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}! I'm smack\n"
	.string "in the middle of a triathlon!\p"
	.string "But, hey, I've always got time to\n"
	.string "shoot the breeze!\p"
	.string "Working out with Pokémon feels\n"
	.string "mighty good!\p"
	.string "Without exchanging words, we synch\n"
	.string "as if we shared a heart.\p"
	.string "It's inspiring!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I'm getting run down…\l"
	.string "Gasp… Have…to…go…$"

MatchCall_PersonalizedText37::
	.string "Hi, it's {STR_VAR_1}.\n"
	.string "If you want to improve endurance,\l"
	.string "high-altitude training is it!\p"
	.string "Try running on a mountaintop.\n"
	.string "You'll be gasping in no time!\p"
	.string "I'm getting oxygen starved, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText38::
	.string "Oh, it's {STR_VAR_1}, hello.\p"
	.string "I've been swimming a lot but I still\n"
	.string "can't seem to reach Evergrande.\p"
	.string "Maybe I'm just going in circles.\p"
	.string "No, no, that can't be possible.\n"
	.string "Wahahaha.\l"
	.string "Take care!$"

MatchCall_PersonalizedText39::
	.string "Hey, it's {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Hey! Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my Pokénav went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "But, boy, Devon's Pokénav is built\n"
	.string "tough. It survived that dunking!\p"
	.string "Anyways, I'm busy sunbathing,\n"
	.string "so let's chat another time.$"

MatchCall_PersonalizedText40::
	.string "Hello, this is {STR_VAR_1}.\p"
	.string "Out of the three triathlon events,\n"
	.string "I like swimming best.\p"
	.string "But if I stay in the sea too long,\n"
	.string "won't I get all prune-like?\p"
	.string "Ooh, triathlon is such a grueling\n"
	.string "test of human endurance! Bye!$"

MatchCall_PersonalizedText41::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How are your Pokémon doing?\p"
	.string "My Dragon Pokémon appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I'm not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText43::
	.string "It is {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of concealment.\p"
	.string "But I have been too successful.\n"
	.string "No one has been able to find me.\l"
	.string "My success makes me lonely…\p"
	.string "Like smoke I disappear!\n"
	.string "Farewell!$"

MatchCall_PersonalizedText44::
	.string "This is {STR_VAR_1}.\n"
	.string "I kept up my training since we met.\p"
	.string "My {STR_VAR_2} is getting pretty\n"
	.string "tough.\p"
	.string "Training on a beach is effective,\n"
	.string "just as I thought. Bye now!$"

MatchCall_PersonalizedText45::
	.string "How do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I wonder when this yucky volcanic\n"
	.string "ash will stop falling?\p"
	.string "If it gets too deep, it will cover\n"
	.string "up the pattern on my parasol…\p"
	.string "Let's promise to meet again!$"

MatchCall_PersonalizedText46::
	.string "Hi, {STR_VAR_1} here.\p"
	.string "Did you know that it's easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "But if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I'm up in the mountains now.\p"
	.string "But the ground is too bumpy.\n"
	.string "I can't pitch my tent here…\p"
	.string "Oh, I had a brilliant idea!\p"
	.string "Maybe I can get my Pokémon to tamp\n"
	.string "the ground flat here!\p"
	.string "I'm going to try that!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48::
	.string "Oh, hi, hi, this is {STR_VAR_1}!\p"
	.string "I'm raising Pokémon with Liv!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "I'm a Sailor, but I'm not on a boat\n"
	.string "now.\p"
	.string "It makes me wonder--what should\n"
	.string "a Sailor on land be called?\p"
	.string "That's what I've been thinking\n"
	.string "while staring out across the waves.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50::
	.string "It's {STR_VAR_1}.\n"
	.string "So? Get any more Pokémon?\p"
	.string "If you catch a new Pokémon,\n"
	.string "you have to come show me.\p"
	.string "I won't whine for it, honest.\n"
	.string "I'll be waiting. See you.$"

MatchCall_PersonalizedText51::
	.string "This is {STR_VAR_1}.\p"
	.string "Are you raising your Pokémon\n"
	.string "in the optimal way?\p"
	.string "The air is clean where I am.\n"
	.string "It's the perfect environment for\l"
	.string "raising Pokémon.\p"
	.string "If you're going to focus on raising\n"
	.string "Pokémon, you should come out to\l"
	.string "{STR_VAR_2}. Take care now.$"

MatchCall_PersonalizedText52::
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like Pokémon have their\n"
	.string "likes and dislikes with {POKEBLOCK}s.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} here.\p"
	.string "If you cooperate with Pokémon,\n"
	.string "one can be comfortable in the wild.\p"
	.string "Everyone should realize that and\n"
	.string "cooperate with Pokémon more.\p"
	.string "That would be ideal.\n"
	.string "I really think so.\p"
	.string "I think you're on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54::
	.string "Hi, it's {STR_VAR_1}. You know,\n"
	.string "the Trainer who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Are your Pokémon fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText55::
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of Trainers every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText56::
	.string "It's me, {STR_VAR_1}.\p"
	.string "I'm popular because I have lots\n"
	.string "of Bug Pokémon, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes Bug Pokémon so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! It's {STR_VAR_1}! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While climbing…\l"
	.string "Is harsh exercise… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "It's steeper now…\l"
	.string "We'll chat…another time…\l"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with Kira!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside Kira.\p"
	.string "Oh, hey, Kira!\n"
	.string "Wh-why are you angry?\p"
	.string "I'm not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59::
	.string "This is {STR_VAR_1}!\p"
	.string "I went to Dewford's Gym again\n"
	.string "for training.\p"
	.string "Brawly, the Gym Leader, seems\n"
	.string "to be tougher now.\p"
	.string "Something about being toughened\n"
	.string "by the wild waves…\p"
	.string "But he's still as cool as ever.\n"
	.string "The ladies adore him!\l"
	.string "It makes me envious, frankly.\p"
	.string "I wonder… Is his friend Bruno\n"
	.string "the same way as Brawly?\p"
	.string "You know, all sweaty or smelly,\n"
	.string "and prone to calling people\l"
	.string "“big wave,” that sort of thing.\p"
	.string "But, hey, this jealousy thing isn't\n"
	.string "very seemly, is it?\p"
	.string "Forget this chat ever happened,\n"
	.string "how about it? So long!$"

MatchCall_PersonalizedText60::
	.string "It's a pleasure to chat with\n"
	.string "a young Trainer like you.\p"
	.string "I imagine that you will continue to\n"
	.string "enjoy Pokémon whatever your age.\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your Pokémon now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61::
	.string "Hi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "We don't win often, but it was this\n"
	.string "cool Swimmer guy.\p"
	.string "My sister was steamed!\p"
	.string "She wanted to pretend that she\n"
	.string "was weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or lose!\p"
	.string "{PLAYER}{KUN}, can you say something\n"
	.string "to her next time?\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here, yes.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I had been hoping to find a new\n"
	.string "ruin to explore.\p"
	.string "But the tides somehow seemed to\n"
	.string "carry me back where I started.\p"
	.string "I'm still weak at battling, too…\n"
	.string "Feel free to mock me…\l"
	.string "But I won't give up.\p"
	.string "My day will come when I discover\n"
	.string "a new ruin!\p"
	.string "That's all I have to say!\n"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63::
	.string "Ahoy there!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "I'm out on Route 108 now!\l"
	.string "In other words, where I always am!\p"
	.string "Today, a gorgeous Swimmer \n"
	.string "swam by me!\p"
	.string "So I startled her with a shout!\p"
	.string "And she gave me a nasty glare!\p"
	.string "That's all from Route 108!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five Trainers again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my Pokémon more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare Pokémon!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare Pokémon!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my Pokémon, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my Pokémon before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare Pokémon lately?\p"
	.string "Oh, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my Pokémon like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my Pokémon and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my Pokémon before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Oh, there goes a rare Pokémon!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my Pokémon like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my Pokémon, too!$"

MatchCall_BattlePyramidText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my Pokémon before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare Pokémon\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my Pokémon like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"
