MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My Pokémon totally rules!\n"
	.string "It's cooler than any Pokémon!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the Chairman\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "Swagger to a Pokémon of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which Pokémon wants to\n"
	.string "learn how to Swagger?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my Pokémon from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your Pokémon will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move Rollout\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the Pokémon looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a Bug-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called Fury Cutter.\n"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on Hidden\n"
	.string "Power to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and Sleep Talk.\p"
	.string "I can teach your Pokémon how to\n"
	.string "Sleep Talk instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with Hidden Power, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I Sleep Talk…$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a Fighting-type Trainer,\n"
	.string "so I can't win at the Mossdeep Gym\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "Pokémon DynamicPunch?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the Mossdeep Gym\n"
	.string "using that DynamicPunch!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge Explosion of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach Explosion to your Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An Explosion it is!\n"
	.string "Which Pokémon wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught Pokémon\n"
	.string "how to use Explosion, but I've yet\l"
	.string "to ignite my own Explosion…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
