gOakDexRatingText_GoodToSeeYou::
	.string "OAK: Good to see you, {PLAYER}!\n"
	.string "How is your Pokédex coming along?\p"
	.string "Here, let me take a look.$"

gOakDexRatingText_AreYouCurious::
	.string "OAK: Good to hear from you you,\n"
	.string "{PLAYER}!\p"
	.string "How is your Pokédex coming along?\p"
	.string "Let's take a look...$"

gOakDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "Pokémon to make it worthwhile.$"

gOakDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} Pokémon…$"

gOakDexRatingText_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

gOakDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gOakDexRatingText_LessThan30::
	.string "Some Pokémon only appear in\n"
	.string "certain areas or times of day.\l"
	.string "You must be persistent.$"

gOakDexRatingText_LessThan40::
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a Pokédex now.$"

gOakDexRatingText_LessThan50::
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gOakDexRatingText_LessThan60::
	.string "Are you using any Rods?\n"
	.string "There are many Pokémon in the sea.$"

gOakDexRatingText_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable Pokédex!$"

gOakDexRatingText_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "Pokémon by going fishing!$"

gOakDexRatingText_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

gOakDexRatingText_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

gOakDexRatingText_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

gOakDexRatingText_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of Pokémon! Super!$"

gOakDexRatingText_LessThan130::
	.string "Excellent! Some Pokémon have very\n"
	.string "unique ways to evolve. You might\l"
	.string "need to seek those out!$"

gOakDexRatingText_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

gOakDexRatingText_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the Pokémon Professor now!$"

gOakDexRatingText_LessThan151::
	.string "I heard some children talking\n"
	.string "about how some rare Pokémon like\l"
	.string "to hide underneath trucks!\p"
	.string "I don't believe them, though.$"

gOakDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the Pokémon of the Hoenn region\l"
	.string "by looking through your Pokédex.$"

gOakDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a Pokémon Professor, and a good\l"
	.string "one, too!$"

gOakDexRatingText_LessThan190::
	.string "With a Pokédex this complete,\n"
	.string "you're a real professional at this!$"

gOakDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this Pokédex.\l"
	.string "I can feel it in my bones!$"

gOakDexRatingText_DexCompleted::
	.string "Your Pokédex is entirely complete!\n"
	.string "Congratulations!!$"
