CeruleanCity_House1_MapScripts::
	.byte 0

CeruleanCity_House1_EventScript_BadgeGuy::
	msgbox CeruleanCity_House1_Text_BadgesHaveAmazingSecrets, MSGBOX_NPC
	release
	end

CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
	.string "Bades are more than just a cool pin!\p"
	.string "A badge certifies a Trainer to use\n"
	.string "certain Hidden Moves, like Flash or\l"
	.string "Fly.\p"
	.string "Pokémon seem to understand their\n"
	.string "importance as well.\p"
	.string "Higher level Pokémon won't obey you\n"
	.string "if you don't have enough badges!$"

CeruleanCity_House1_EventScript_BulbasaurBreeder::
	msgbox CeruleanCity_House1_Text_HowsThatBulbasaur, MSGBOX_NPC
	release
	end

CeruleanCity_House1_Text_HowsThatBulbasaur::
	.string "How is that Bulbasaur getting\n"
	.string "along with your Pokémon?\p"
	.string "I hope you're treating it well!$"
