CinnabarIsland_Lab_Entrance_MapScripts::
	.byte 0

CinnabarIsland_PokemonLab_Entrance_EventScript_Scientist::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively, MSGBOX_NPC
    end

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "We study Pokémon extensively\n"
    .string "every day.\p"
    .string "People often bring us rare Pokémon\n"
    .string "for examination.$"

CinnabarIsland_PokemonLab_Entrance_EventScript_DrFujiPhoto::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "A photo of the Lab's founder…\n"
    .string "Dr. Fuji?!$"

CinnabarIsland_PokemonLab_Entrance_EventScript_MeetingRoomSign::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "Pokémon Lab\n"
    .string "Meeting Room$"

CinnabarIsland_PokemonLab_Entrance_EventScript_RAndDRoomSign::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "Pokémon Lab\n"
    .string "R & D Room$"

CinnabarIsland_PokemonLab_Entrance_EventScript_TestingRoomSign::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "Pokémon Lab\n"
    .string "Testing Room$"
