DiglettsCave_NorthEntrance_MapScripts::
	.byte 0

DiglettsCave_NorthEntrance_EventScript_Hiker::
	msgbox DiglettsCave_NorthEntrance_RockTunnelPitchBlack, MSGBOX_NPC
	end

DiglettsCave_NorthEntrance_RockTunnelPitchBlack::
    .string "I went inside Rock Tunnel, but it's\n"
    .string "pitch-black and scary in there.\p"
    .string "If I could get a Pokémon to use\n"
    .string "Flash and light it up…$"
