FuchsiaCity_House3_MapScripts::
	.byte 0

FuchsiaCity_House3_EventScript_MoveDeleter::
	msgbox FuchsiaCity_House3_Text_WouldYouLikeToForgetMove, MSGBOX_NPC
	release
	end

FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh…\n"
    .string "Oh, yes, I'm the Move Deleter.\p"
    .string "Have you met the Move Deleters\n"
    .string "at the Pokémon League Services?\p"
    .string "They're my students! I taught\n"
    .string "them everything they know.\p"
    .string "Hopefully they don't forget!$"
