CeladonCity_House1_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe!\p"
    .string "The slots just reel in the dough,\n"
    .string "big-time!$"

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "Chief!\p"
    .string "We just shipped two thousand\n"
    .string "more Pokémon Dolls as slot prizes\l"
    .string "again today!\p"
    .string "And we're arranging buyers for the\n"
    .string "Pokémon we kidnapped, too.$"

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Don't touch the poster at the Game\n"
    .string "Corner!\p"
    .string "There's no secret switch behind it!$"

CeladonCity_House1_EventScript_PoliceChief::
    msgbox CeladonCity_House1_Text_BustedTheseRockets, MSGBOX_NPC
    end

CeladonCity_House1_Text_BustedTheseRockets::
    .string "We've finally busted the leaders\n"
    .string "of this operation.$"

CeladonCity_House1_EventScript_Police1::
    msgbox CeladonCity_House1_Text_DontStepOnEvidence, MSGBOX_NPC
    end

CeladonCity_House1_Text_DontStepOnEvidence::
    .string "Hey! Watch it, kid!\n"
    .string "We're collecting evidence.$"

CeladonCity_House1_EventScript_Police2::
    msgbox CeladonCity_House1_Text_WhoDoesThat, MSGBOX_NPC
    end

CeladonCity_House1_Text_WhoDoesThat::
    .string "Kidnapping and selling Pokémon?\n"
    .string "What kind of menace does that!$"
