#ifndef GUARD_TRAINER_REMATCH_H
#define GUARD_TRAINER_REMATCH_H

enum {
    REMATCH_JANICE,
    REMATCH_BEN,
    REMATCH_SHANE,
    REMATCH_FRANKLIN,
    REMATCH_KEIGO,
    REMATCH_HUGO,
    REMATCH_BERNIE,
    REMATCH_NED,
    REMATCH_LUCA,
    //
    REMATCH_UNUSED_9,
    REMATCH_UNUSED_10,
    REMATCH_UNUSED_11,
    REMATCH_UNUSED_12,
    REMATCH_UNUSED_13,
    REMATCH_UNUSED_14,
    REMATCH_UNUSED_15,
    REMATCH_UNUSED_16,
    REMATCH_UNUSED_17,
    REMATCH_UNUSED_18,
    REMATCH_UNUSED_19,
    REMATCH_UNUSED_20,
    REMATCH_UNUSED_21,
    REMATCH_UNUSED_22,
    REMATCH_UNUSED_23,
    REMATCH_UNUSED_24,
    REMATCH_UNUSED_25,
    REMATCH_UNUSED_26,
    REMATCH_UNUSED_27,
    REMATCH_UNUSED_28,
    REMATCH_UNUSED_29,
    REMATCH_UNUSED_30,
    REMATCH_UNUSED_31,
    REMATCH_UNUSED_32,
    REMATCH_UNUSED_33,
    REMATCH_UNUSED_34,
    REMATCH_UNUSED_35,
    REMATCH_UNUSED_36,
    REMATCH_UNUSED_37,
    REMATCH_UNUSED_38,
    REMATCH_UNUSED_39,
    REMATCH_UNUSED_40,
    REMATCH_UNUSED_41,
    REMATCH_UNUSED_42,
    REMATCH_UNUSED_43,
    REMATCH_UNUSED_44,
    REMATCH_UNUSED_45,
    REMATCH_UNUSED_46,
    REMATCH_UNUSED_47,
    REMATCH_UNUSED_48,
    REMATCH_UNUSED_49,
    REMATCH_UNUSED_50,
    REMATCH_UNUSED_51,
    REMATCH_UNUSED_52,
    REMATCH_UNUSED_53,
    REMATCH_UNUSED_54,
    REMATCH_UNUSED_55,
    REMATCH_UNUSED_56,
    REMATCH_UNUSED_57,
    REMATCH_UNUSED_58,
    REMATCH_UNUSED_59,
    REMATCH_UNUSED_60,
    REMATCH_UNUSED_61,
    REMATCH_UNUSED_62,
    REMATCH_UNUSED_63,
    REMATCH_SPECIAL_TRAINER, //Entries above this are considered normal trainers, from here below are special trainers
    REMATCH_ELITE_FOUR, // Entries from SIDNEY below are considered part of REMATCH_ELITE_FOUR_ENTRIES. 
    REMATCH_TABLE_ENTRIES // The total number of rematch entries. Must be last in enum
};

#define REMATCH_SPECIAL_TRAINER_START   REMATCH_SPECIAL_TRAINER
#define REMATCH_ELITE_FOUR_ENTRIES      REMATCH_ELITE_FOUR

void UpdateGymLeaderRematch(void);

#endif //GUARD_TRAINER_REMATCH_H
