DiglettsCave_SouthEntrance_MapScripts::
	.byte 0

DiglettsCave_SouthEntrance_EventScript_OldMan::
	msgbox DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel, MSGBOX_NPC
	end

DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
    .string "Well, isn't this a surprise!\n"
    .string "Diglett dug this long tunnel!\p"
    .string "It goes right to Viridian City,\n"
    .string "they tell me.$"
