	.align 2
gTilesetTiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/15.gbapal"

	.align 2
gTilesetTiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dewford::
	.incbin "data/tilesets/secondary/dewford/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/15.gbapal"

	.align 2
gTilesetTiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Slateport::
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mauville::
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fortree::
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2
gTilesetTiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2
gTilesetTiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2
gTilesetTiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding::
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Shop::
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop::
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave::
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave::
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/15.gbapal"

	.align 2
gTilesetTiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2
gTilesetTiles_Facility::
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Facility::
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/15.gbapal"

	.align 2
gTilesetTiles_Contest::
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest::
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2
gTilesetTiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab::
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab::
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underwater::
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase::
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase::
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetTiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"

	.align 2
gTilesetTiles_PalletTown:: @ 826D37C
	.incbin "data/tilesets/secondary/pallet_town/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PalletTown:: @ 826D7C0
	.incbin "data/tilesets/secondary/pallet_town/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pallet_town/palettes/15.gbapal"

	.align 2
gTilesetTiles_ViridianCity:: @ 826D9C0
	.incbin "data/tilesets/secondary/viridian_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCity:: @ 826DFC0
	.incbin "data/tilesets/secondary/viridian_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/viridian_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_PewterCity:: @ 826E1C0
	.incbin "data/tilesets/secondary/pewter_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCity:: @ 826EAB8
	.incbin "data/tilesets/secondary/pewter_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pewter_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeruleanCity:: @ 826ECB8
	.incbin "data/tilesets/secondary/cerulean_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCity:: @ 826F4B8
	.incbin "data/tilesets/secondary/cerulean_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cerulean_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavenderTown:: @ 826F6B8
	.incbin "data/tilesets/secondary/lavender_town/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavenderTown:: @ 8270438
	.incbin "data/tilesets/secondary/lavender_town/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavender_town/palettes/15.gbapal"

	.align 2
gTilesetTiles_VermilionCity:: @ 8270638
	.incbin "data/tilesets/secondary/vermilion_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCity:: @ 8270DA0
	.incbin "data/tilesets/secondary/vermilion_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/vermilion_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeladonCity:: @ 8270FA0
	.incbin "data/tilesets/secondary/celadon_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCity:: @ 8271C74
	.incbin "data/tilesets/secondary/celadon_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/celadon_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_FuchsiaCity:: @ 8271E74
	.incbin "data/tilesets/secondary/fuchsia_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCity:: @ 8272A5C
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_CinnabarIsland:: @ 8272C5C
	.incbin "data/tilesets/secondary/cinnabar_island/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarIsland:: @ 8273358
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_island/palettes/15.gbapal"

	.align 2
gTilesetTiles_IndigoPlateau:: @ 8273558
	.incbin "data/tilesets/secondary/indigo_plateau/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IndigoPlateau:: @ 82742D0
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/indigo_plateau/palettes/15.gbapal"

	.align 2
gTilesetTiles_SaffronCity:: @ 82744D0
	.incbin "data/tilesets/secondary/saffron_city/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCity:: @ 8275094
	.incbin "data/tilesets/secondary/saffron_city/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/saffron_city/palettes/15.gbapal"

	.align 2
gTilesetTiles_Building:: @ Building
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Building:: @ Building
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mart:: @ 8277894
	.incbin "data/tilesets/secondary/mart/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mart:: @ 8277A5C
	.incbin "data/tilesets/secondary/mart/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mart/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy1:: @ 827A3A8
	.incbin "data/tilesets/secondary/dummy_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy1:: @ 827A3B8
	.incbin "data/tilesets/secondary/dummy_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_Museum:: @ 827A5B8
	.incbin "data/tilesets/secondary/museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Museum:: @ 827AE14
	.incbin "data/tilesets/secondary/museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_HoennBuilding:: @ 8280F00
	.incbin "data/tilesets/secondary/hoenn_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_HoennBuilding:: @ 82823A4
	.incbin "data/tilesets/secondary/hoenn_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/hoenn_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_GameCorner:: @ 82825A4
	.incbin "data/tilesets/secondary/game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GameCorner:: @ 8282FBC
	.incbin "data/tilesets/secondary/game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_PewterGym:: @ 82831BC
	.incbin "data/tilesets/secondary/pewter_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterGym:: @ 82839B0
	.incbin "data/tilesets/secondary/pewter_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pewter_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeruleanGym:: @ 8283BB0
	.incbin "data/tilesets/secondary/cerulean_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanGym:: @ 8283FF8
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cerulean_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_VermilionGym:: @ 82841F8
	.incbin "data/tilesets/secondary/vermilion_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionGym:: @ 82849B8
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/vermilion_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeladonGym:: @ 8284BB8
	.incbin "data/tilesets/secondary/celadon_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonGym:: @ 8285150
	.incbin "data/tilesets/secondary/celadon_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/celadon_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FuchsiaGym:: @ 8285350
	.incbin "data/tilesets/secondary/fuchsia_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaGym:: @ 82857A4
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fuchsia_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SaffronGym:: @ 82859A4
	.incbin "data/tilesets/secondary/saffron_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronGym:: @ 8285D90
	.incbin "data/tilesets/secondary/saffron_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/saffron_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_CinnabarGym:: @ 8285F90
	.incbin "data/tilesets/secondary/cinnabar_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarGym:: @ 82865D4
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cinnabar_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_ViridianGym:: @ 82867D4
	.incbin "data/tilesets/secondary/viridian_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianGym:: @ 8286BC8
	.incbin "data/tilesets/secondary/viridian_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/viridian_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SSAnne:: @ 8286DC8
	.incbin "data/tilesets/secondary/ss_anne/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SSAnne:: @ 8287B80
	.incbin "data/tilesets/secondary/ss_anne/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ss_anne/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy2:: @ 8287D80
	.incbin "data/tilesets/secondary/dummy_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy2:: @ 8287D94
	.incbin "data/tilesets/secondary/dummy_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_ViridianForest:: @ 8287F94
	.incbin "data/tilesets/secondary/viridian_forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianForest:: @ 8288444
	.incbin "data/tilesets/secondary/viridian_forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/viridian_forest/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnusedGatehouse1:: @ 8288644
	.incbin "data/tilesets/secondary/unused_gatehouse_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UnusedGatehouse1:: @ 8288C60
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_RockTunnel:: @ 8288E60
	.incbin "data/tilesets/secondary/rock_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RockTunnel:: @ 8289FC8
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rock_tunnel/palettes/15.gbapal"

	.align 2
gTilesetTiles_DiglettsCave:: @ 828A1C8
	.incbin "data/tilesets/secondary/digletts_cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DiglettsCave:: @ 828B250
	.incbin "data/tilesets/secondary/digletts_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/digletts_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeafoamIslands:: @ 828B450
	.incbin "data/tilesets/secondary/seafoam_islands/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeafoamIslands:: @ 828CAA0
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seafoam_islands/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnusedGatehouse2:: @ 828CCA0
	.incbin "data/tilesets/secondary/unused_gatehouse_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UnusedGatehouse2:: @ 828D2BC
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_gatehouse_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_CeruleanCave:: @ 828D4BC
	.incbin "data/tilesets/secondary/cerulean_cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCave:: @ 828E3A4
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cerulean_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding2:: @ 828E5A4
	.incbin "data/tilesets/secondary/generic_building_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding2:: @ 828EC70
	.incbin "data/tilesets/secondary/generic_building_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_PowerPlant:: @ 828EE70
	.incbin "data/tilesets/secondary/power_plant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PowerPlant:: @ 828F378
	.incbin "data/tilesets/secondary/power_plant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/power_plant/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeaCottage:: @ 828F578
	.incbin "data/tilesets/secondary/sea_cottage/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeaCottage:: @ 828F9D8
	.incbin "data/tilesets/secondary/sea_cottage/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sea_cottage/palettes/15.gbapal"

	.align 2
gTilesetTiles_SilphCo:: @ 828FBD8
	.incbin "data/tilesets/secondary/condominiums/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SilphCo:: @ 8290DD0
	.incbin "data/tilesets/secondary/condominiums/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/15.gbapal"

	.align 2
gTilesetTiles_UndergroundPath:: @ 8290FD0
	.incbin "data/tilesets/secondary/underground_path/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UndergroundPath:: @ 8291274
	.incbin "data/tilesets/secondary/underground_path/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underground_path/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonTower:: @ 8291474
	.incbin "data/tilesets/secondary/pokemon_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonTower:: @ 8291AFC
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_SafariZoneBuilding:: @ 8291CFC
	.incbin "data/tilesets/secondary/safari_zone_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SafariZoneBuilding:: @ 82920F0
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/safari_zone_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonMansion:: @ 82922F0
	.incbin "data/tilesets/secondary/pokemon_mansion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonMansion:: @ 8292FF0
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_mansion/palettes/15.gbapal"

	.align 2
gTilesetTiles_RestaurantHotel:: @ 82931F0
	.incbin "data/tilesets/secondary/restaurant_hotel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RestaurantHotel:: @ 8293660
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/restaurant_hotel/palettes/15.gbapal"

	.align 2
gTilesetTiles_School:: @ 8293860
	.incbin "data/tilesets/secondary/school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_School:: @ 8293B0C
	.incbin "data/tilesets/secondary/school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/school/palettes/15.gbapal"

	.align 2
gTilesetTiles_FanClubDaycare:: @ 8293D0C
	.incbin "data/tilesets/secondary/fan_club_daycare/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FanClubDaycare:: @ 8294144
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fan_club_daycare/palettes/15.gbapal"

	.align 2
gTilesetTiles_BurgledHouse:: @ 8294344
	.incbin "data/tilesets/secondary/burgled_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BurgledHouse:: @ 8294D08
	.incbin "data/tilesets/secondary/burgled_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/burgled_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy3:: @ 8294F08
	.incbin "data/tilesets/secondary/dummy_3/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy3:: @ 8294F18
	.incbin "data/tilesets/secondary/dummy_3/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_3/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dummy4:: @ 8295118
	.incbin "data/tilesets/secondary/dummy_4/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dummy4:: @ 829512C
	.incbin "data/tilesets/secondary/dummy_4/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dummy_4/palettes/15.gbapal"

	.align 2
gTilesetTiles_MtEmber:: @ 829532C
	.incbin "data/tilesets/secondary/mt_ember/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MtEmber:: @ 82967D4
	.incbin "data/tilesets/secondary/mt_ember/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mt_ember/palettes/15.gbapal"

	.align 2
gTilesetTiles_BerryForest:: @ 82969D4
	.incbin "data/tilesets/secondary/berry_forest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BerryForest:: @ 8296E90
	.incbin "data/tilesets/secondary/berry_forest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/berry_forest/palettes/15.gbapal"

	.align 2
gTilesetTiles_TanobyRuins:: @ 82985BC
	.incbin "data/tilesets/secondary/tanoby_ruins/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TanobyRuins:: @ 8298970
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/tanoby_ruins/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeviiIslands123:: @ 8298B70
	.incbin "data/tilesets/secondary/sevii_islands_123/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIslands123:: @ 8299AA4
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_123/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeviiIslands45:: @ 8299CA4
	.incbin "data/tilesets/secondary/sevii_islands_45/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIslands45:: @ 829AB04
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_45/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeviiIslands67:: @ 829AD04
	.incbin "data/tilesets/secondary/sevii_islands_67/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIslands67:: @ 829BD64
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sevii_islands_67/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerTower:: @ 829BF64
	.incbin "data/tilesets/secondary/trainer_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerTower:: @ 829CEE4
	.incbin "data/tilesets/secondary/trainer_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonLeague:: @ 829DA94
	.incbin "data/tilesets/secondary/pokemon_league/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonLeague:: @ 829EA50
	.incbin "data/tilesets/secondary/pokemon_league/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_league/palettes/15.gbapal"

	.align 2
gTilesetTiles_HallOfFame:: @ 829EC50
	.incbin "data/tilesets/secondary/hall_of_fame/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_HallOfFame:: @ 829F4C8
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/hall_of_fame/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding1::
	.incbin "data/tilesets/secondary/generic_building_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding1::
    .incbin "data/tilesets/secondary/generic_building_1/palettes/00.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/01.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/02.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/03.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/04.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/05.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/06.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/07.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/08.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/09.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/generic_building_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_DepartmentStore::
	.incbin "data/tilesets/secondary/department_store/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DepartmentStore::
    .incbin "data/tilesets/secondary/department_store/palettes/00.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/01.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/02.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/03.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/04.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/05.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/06.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/07.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/08.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/09.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/10.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/11.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/12.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/13.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/14.gbapal"
    .incbin "data/tilesets/secondary/department_store/palettes/15.gbapal"
