	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatiles.bin"

	.align 1
gMetatileAttributes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes.bin"

	.align 1
gMetatiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatiles.bin"

	.align 1
gMetatileAttributes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_attributes.bin"

	.align 1
gMetatiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatiles.bin"

	.align 1
gMetatileAttributes_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_attributes.bin"

	.align 1
gMetatiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatiles.bin"

	.align 1
gMetatileAttributes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_attributes.bin"

	.align 1
gMetatiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Shop::
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_attributes.bin"

	.align 1
gMetatiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatiles.bin"

	.align 1
gMetatileAttributes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_attributes.bin"

	.align 1
gMetatiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatiles.bin"

	.align 1
gMetatileAttributes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_attributes.bin"

	.align 1
gMetatiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatiles.bin"

	.align 1
gMetatileAttributes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatiles.bin"

	.align 1
gMetatileAttributes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_attributes.bin"

	.align 1
gMetatiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatiles.bin"

	.align 1
gMetatileAttributes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatiles_Facility::
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatiles.bin"

	.align 1
gMetatileAttributes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_attributes.bin"

	.align 1
gMetatiles_Contest::
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatiles.bin"

	.align 1
gMetatileAttributes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_attributes.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatiles.bin"

	.align 1
gMetatileAttributes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_attributes.bin"

	.align 1
gMetatiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatiles.bin"

	.align 1
gMetatileAttributes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_attributes.bin"

	.align 1
gMetatiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatiles.bin"

	.align 1
gMetatileAttributes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

	.align 1
gMetatiles_PalletTown:: @ 82A28C8
	.incbin "data/tilesets/secondary/pallet_town/metatiles.bin"

	.align 1
gMetatileAttributes_PalletTown:: @ 82A2E58
	.incbin "data/tilesets/secondary/pallet_town/metatile_attributes.bin"

	.align 1
gMetatiles_ViridianCity:: @ 82A2FBC
	.incbin "data/tilesets/secondary/viridian_city/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianCity:: @ 82A35AC
	.incbin "data/tilesets/secondary/viridian_city/metatile_attributes.bin"

	.align 1
gMetatiles_PewterCity:: @ 82A3728
	.incbin "data/tilesets/secondary/pewter_city/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCity:: @ 82A3C18
	.incbin "data/tilesets/secondary/pewter_city/metatile_attributes.bin"

	.align 1
gMetatiles_CeruleanCity:: @ 82A3D54
	.incbin "data/tilesets/secondary/cerulean_city/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCity:: @ 82A45B4
	.incbin "data/tilesets/secondary/cerulean_city/metatile_attributes.bin"

	.align 1
gMetatiles_LavenderTown:: @ 82A47CC
	.incbin "data/tilesets/secondary/lavender_town/metatiles.bin"

	.align 1
gMetatileAttributes_LavenderTown:: @ 82A556C
	.incbin "data/tilesets/secondary/lavender_town/metatile_attributes.bin"

	.align 1
gMetatiles_VermilionCity:: @ 82A58D4
	.incbin "data/tilesets/secondary/vermilion_city/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionCity:: @ 82A6354
	.incbin "data/tilesets/secondary/vermilion_city/metatile_attributes.bin"

	.align 1
gMetatiles_CeladonCity:: @ 82A65F4
	.incbin "data/tilesets/secondary/celadon_city/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonCity:: @ 82A74F4
	.incbin "data/tilesets/secondary/celadon_city/metatile_attributes.bin"

	.align 1
gMetatiles_FuchsiaCity:: @ 82A78B4
	.incbin "data/tilesets/secondary/fuchsia_city/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaCity:: @ 82A84B4
	.incbin "data/tilesets/secondary/fuchsia_city/metatile_attributes.bin"

	.align 1
gMetatiles_CinnabarIsland:: @ 82A87B4
	.incbin "data/tilesets/secondary/cinnabar_island/metatiles.bin"

	.align 1
gMetatileAttributes_CinnabarIsland:: @ 82A8BB4
	.incbin "data/tilesets/secondary/cinnabar_island/metatile_attributes.bin"

	.align 1
gMetatiles_IndigoPlateau:: @ 82A8CB4
	.incbin "data/tilesets/secondary/indigo_plateau/metatiles.bin"

	.align 1
gMetatileAttributes_IndigoPlateau:: @ 82A97B4
	.incbin "data/tilesets/secondary/indigo_plateau/metatile_attributes.bin"

	.align 1
gMetatiles_SaffronCity:: @ 82A9A74
	.incbin "data/tilesets/secondary/saffron_city/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronCity:: @ 82AA6F4
	.incbin "data/tilesets/secondary/saffron_city/metatile_attributes.bin"

	.align 1
gMetatiles_PewterGym:: @ 82AAA14
	.incbin "data/tilesets/secondary/pewter_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PewterGym:: @ 82AB064
	.incbin "data/tilesets/secondary/pewter_gym/metatile_attributes.bin"

	.align 1
gMetatiles_CeruleanGym:: @ 82AB1F8
	.incbin "data/tilesets/secondary/cerulean_gym/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanGym:: @ 82AB738
	.incbin "data/tilesets/secondary/cerulean_gym/metatile_attributes.bin"

	.align 1
gMetatiles_VermilionGym:: @ 82AB888
	.incbin "data/tilesets/secondary/vermilion_gym/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionGym:: @ 82ABD38
	.incbin "data/tilesets/secondary/vermilion_gym/metatile_attributes.bin"

	.align 1
gMetatiles_CeladonGym:: @ 82ABE64
	.incbin "data/tilesets/secondary/celadon_gym/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonGym:: @ 82AC264
	.incbin "data/tilesets/secondary/celadon_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FuchsiaGym:: @ 82AC364
	.incbin "data/tilesets/secondary/fuchsia_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaGym:: @ 82AC584
	.incbin "data/tilesets/secondary/fuchsia_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SaffronGym:: @ 82AC60C
	.incbin "data/tilesets/secondary/saffron_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronGym:: @ 82AC8EC
	.incbin "data/tilesets/secondary/saffron_gym/metatile_attributes.bin"

	.align 1
gMetatiles_CinnabarGym:: @ 82AC9A4
	.incbin "data/tilesets/secondary/cinnabar_gym/metatiles.bin"

	.align 1
gMetatileAttributes_CinnabarGym:: @ 82ACFA4
	.incbin "data/tilesets/secondary/cinnabar_gym/metatile_attributes.bin"

	.align 1
gMetatiles_ViridianGym:: @ 82AD124
	.incbin "data/tilesets/secondary/viridian_gym/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianGym:: @ 82AD664
	.incbin "data/tilesets/secondary/viridian_gym/metatile_attributes.bin"

	.align 1
gMetatiles_Building:: @ Building
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_Building:: @ Building
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy1:: @ 82B09B4
	.incbin "data/tilesets/secondary/dummy_1/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy1:: @ 82B09D4
	.incbin "data/tilesets/secondary/dummy_1/metatile_attributes.bin"

	.align 1
gMetatiles_HoennBuilding:: @ 82B09DC
	.incbin "data/tilesets/secondary/hoenn_building/metatiles.bin"

	.align 1
gMetatileAttributes_HoennBuilding:: @ 82B29DC
	.incbin "data/tilesets/secondary/hoenn_building/metatile_attributes.bin"

	.align 1
gMetatiles_Mart:: @ 82B3524
	.incbin "data/tilesets/secondary/mart/metatiles.bin"

	.align 1
gMetatileAttributes_Mart:: @ 82B3954
	.incbin "data/tilesets/secondary/mart/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding1:: @ 82B4E4C
	.incbin "data/tilesets/secondary/generic_building_1/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding1:: @ 82B4FCC
	.incbin "data/tilesets/secondary/generic_building_1/metatile_attributes.bin"

	.align 1
gMetatiles_GameCorner:: @ 82B5CC0
	.incbin "data/tilesets/secondary/game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_GameCorner:: @ 82B6640
	.incbin "data/tilesets/secondary/game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_SSAnne:: @ 82B764C
	.incbin "data/tilesets/secondary/ss_anne/metatiles.bin"

	.align 1
gMetatileAttributes_SSAnne:: @ 82B8B4C
	.incbin "data/tilesets/secondary/ss_anne/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy2:: @ 82B908C
	.incbin "data/tilesets/secondary/dummy_2/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy2:: @ 82B90AC
	.incbin "data/tilesets/secondary/dummy_2/metatile_attributes.bin"

	.align 1
gMetatiles_ViridianForest:: @ 82B90B4
	.incbin "data/tilesets/secondary/viridian_forest/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianForest:: @ 82B9364
	.incbin "data/tilesets/secondary/viridian_forest/metatile_attributes.bin"

	.align 1
gMetatiles_UnusedGatehouse1:: @ 82B9410
	.incbin "data/tilesets/secondary/unused_gatehouse_1/metatiles.bin"

	.align 1
gMetatileAttributes_UnusedGatehouse1:: @ 82B9B30
	.incbin "data/tilesets/secondary/unused_gatehouse_1/metatile_attributes.bin"

	.align 1
gMetatiles_RockTunnel:: @ 82B9CF8
	.incbin "data/tilesets/secondary/rock_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RockTunnel:: @ 82BA678
	.incbin "data/tilesets/secondary/rock_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_DiglettsCave:: @ 82BA8D8
	.incbin "data/tilesets/secondary/digletts_cave/metatiles.bin"

	.align 1
gMetatileAttributes_DiglettsCave:: @ 82BB2A8
	.incbin "data/tilesets/secondary/digletts_cave/metatile_attributes.bin"

	.align 1
gMetatiles_SeafoamIslands:: @ 82BB51C
	.incbin "data/tilesets/secondary/seafoam_islands/metatiles.bin"

	.align 1
gMetatileAttributes_SeafoamIslands:: @ 82BC49C
	.incbin "data/tilesets/secondary/seafoam_islands/metatile_attributes.bin"

	.align 1
gMetatiles_UnusedGatehouse2:: @ 82BC87C
	.incbin "data/tilesets/secondary/unused_gatehouse_2/metatiles.bin"

	.align 1
gMetatileAttributes_UnusedGatehouse2:: @ 82BCF9C
	.incbin "data/tilesets/secondary/unused_gatehouse_2/metatile_attributes.bin"

	.align 1
gMetatiles_CeruleanCave:: @ 82BD164
	.incbin "data/tilesets/secondary/cerulean_cave/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCave:: @ 82BD9C4
	.incbin "data/tilesets/secondary/cerulean_cave/metatile_attributes.bin"

	.align 1
gMetatiles_DepartmentStore:: @ 82BDBDC
	.incbin "data/tilesets/secondary/department_store/metatiles.bin"

	.align 1
gMetatileAttributes_DepartmentStore:: @ 82BEB3C
	.incbin "data/tilesets/secondary/department_store/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding2:: @ 82BEF14
	.incbin "data/tilesets/secondary/generic_building_2/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding2:: @ 82BFA94
	.incbin "data/tilesets/secondary/generic_building_2/metatile_attributes.bin"

	.align 1
gMetatiles_PowerPlant:: @ 82BFD74
	.incbin "data/tilesets/secondary/power_plant/metatiles.bin"

	.align 1
gMetatileAttributes_PowerPlant:: @ 82C0704
	.incbin "data/tilesets/secondary/power_plant/metatile_attributes.bin"

	.align 1
gMetatiles_SeaCottage:: @ 82C0968
	.incbin "data/tilesets/secondary/sea_cottage/metatiles.bin"

	.align 1
gMetatileAttributes_SeaCottage:: @ 82C0D18
	.incbin "data/tilesets/secondary/sea_cottage/metatile_attributes.bin"

	.align 1
gMetatiles_SilphCo:: @ 82C0E04
	.incbin "data/tilesets/secondary/silph_co/metatiles.bin"

	.align 1
gMetatileAttributes_SilphCo:: @ 82C25A4
	.incbin "data/tilesets/secondary/silph_co/metatile_attributes.bin"

	.align 1
gMetatiles_UndergroundPath:: @ 82C2B8C
	.incbin "data/tilesets/secondary/underground_path/metatiles.bin"

	.align 1
gMetatileAttributes_UndergroundPath:: @ 82C300C
	.incbin "data/tilesets/secondary/underground_path/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonTower:: @ 82C312C
	.incbin "data/tilesets/secondary/pokemon_tower/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonTower:: @ 82C377C
	.incbin "data/tilesets/secondary/pokemon_tower/metatile_attributes.bin"

	.align 1
gMetatiles_SafariZoneBuilding:: @ 82C3910
	.incbin "data/tilesets/secondary/safari_zone_building/metatiles.bin"

	.align 1
gMetatileAttributes_SafariZoneBuilding:: @ 82C4110
	.incbin "data/tilesets/secondary/safari_zone_building/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonMansion:: @ 82C4310
	.incbin "data/tilesets/secondary/pokemon_mansion/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonMansion:: @ 82C5330
	.incbin "data/tilesets/secondary/pokemon_mansion/metatile_attributes.bin"

	.align 1
gMetatiles_Museum:: @ 82C5738
	.incbin "data/tilesets/secondary/museum/metatiles.bin"

	.align 1
gMetatileAttributes_Museum:: @ 82C5FA8
	.incbin "data/tilesets/secondary/museum/metatile_attributes.bin"

	.align 1
gMetatiles_RestaurantHotel:: @ 82C75C4
	.incbin "data/tilesets/secondary/restaurant_hotel/metatiles.bin"

	.align 1
gMetatileAttributes_RestaurantHotel:: @ 82C7C44
	.incbin "data/tilesets/secondary/restaurant_hotel/metatile_attributes.bin"

	.align 1
gMetatiles_School:: @ 82C7DE4
	.incbin "data/tilesets/secondary/school/metatiles.bin"

	.align 1
gMetatileAttributes_School:: @ 82C80C4
	.incbin "data/tilesets/secondary/school/metatile_attributes.bin"

	.align 1
gMetatiles_FanClubDaycare:: @ 82C817C
	.incbin "data/tilesets/secondary/fan_club_daycare/metatiles.bin"

	.align 1
gMetatileAttributes_FanClubDaycare:: @ 82C8C1C
	.incbin "data/tilesets/secondary/fan_club_daycare/metatile_attributes.bin"

	.align 1
gMetatiles_Condominiums:: @ 82C8EC4
	.incbin "data/tilesets/secondary/condominiums/metatiles.bin"

	.align 1
gMetatileAttributes_Condominiums:: @ 82C9C34
	.incbin "data/tilesets/secondary/condominiums/metatile_attributes.bin"

	.align 1
gMetatiles_BurgledHouse:: @ 82C9F90
	.incbin "data/tilesets/secondary/burgled_house/metatiles.bin"

	.align 1
gMetatileAttributes_BurgledHouse:: @ 82CA320
	.incbin "data/tilesets/secondary/burgled_house/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy3:: @ 82CA404
	.incbin "data/tilesets/secondary/dummy_3/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy3:: @ 82CA424
	.incbin "data/tilesets/secondary/dummy_3/metatile_attributes.bin"

	.align 1
gMetatiles_Dummy4:: @ 82CA42C
	.incbin "data/tilesets/secondary/dummy_4/metatiles.bin"

	.align 1
gMetatileAttributes_Dummy4:: @ 82CA44C
	.incbin "data/tilesets/secondary/dummy_4/metatile_attributes.bin"

	.align 1
gMetatiles_MtEmber:: @ 82CA454
	.incbin "data/tilesets/secondary/mt_ember/metatiles.bin"

	.align 1
gMetatileAttributes_MtEmber:: @ 82CB274
	.incbin "data/tilesets/secondary/mt_ember/metatile_attributes.bin"

	.align 1
gMetatiles_BerryForest:: @ 82CB5FC
	.incbin "data/tilesets/secondary/berry_forest/metatiles.bin"

	.align 1
gMetatileAttributes_BerryForest:: @ 82CB89C
	.incbin "data/tilesets/secondary/berry_forest/metatile_attributes.bin"

	.align 1
gMetatiles_TanobyRuins:: @ 82CCA74
	.incbin "data/tilesets/secondary/tanoby_ruins/metatiles.bin"

	.align 1
gMetatileAttributes_TanobyRuins:: @ 82CD054
	.incbin "data/tilesets/secondary/tanoby_ruins/metatile_attributes.bin"

	.align 1
gMetatiles_SeviiIslands123:: @ 82CD1CC
	.incbin "data/tilesets/secondary/sevii_islands_123/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIslands123:: @ 82CE39C
	.incbin "data/tilesets/secondary/sevii_islands_123/metatile_attributes.bin"

	.align 1
gMetatiles_SeviiIslands45:: @ 82CE810
	.incbin "data/tilesets/secondary/sevii_islands_45/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIslands45:: @ 82CF190
	.incbin "data/tilesets/secondary/sevii_islands_45/metatile_attributes.bin"

	.align 1
gMetatiles_SeviiIslands67:: @ 82CF3F0
	.incbin "data/tilesets/secondary/sevii_islands_67/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIslands67:: @ 82D02F0
	.incbin "data/tilesets/secondary/sevii_islands_67/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerTower:: @ 82D06B0
	.incbin "data/tilesets/secondary/trainer_tower/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerTower:: @ 82D18B0
	.incbin "data/tilesets/secondary/trainer_tower/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonLeague:: @ 82D235C
	.incbin "data/tilesets/secondary/pokemon_league/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonLeague:: @ 82D3B5C
	.incbin "data/tilesets/secondary/pokemon_league/metatile_attributes.bin"

	.align 1
gMetatiles_HallOfFame:: @ 82D415C
	.incbin "data/tilesets/secondary/hall_of_fame/metatiles.bin"

	.align 1
gMetatileAttributes_HallOfFame:: @ 82D48BC
	.incbin "data/tilesets/secondary/hall_of_fame/metatile_attributes.bin"
